### PR TITLE
This attempt did not go well, github was simply down

### PR DESCRIPTION
**Pull request by aprokop**

### CODE REVIEW

**Comment by aprokop** [comment]
Workflow is up and running, good.

**Comment by masterleinad** [comment]
Just
```
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://code.ornl.gov/ecpcitest/alexa.git/'
Triggered CI for branch remove_stupidity
```
as expected.

**Comment by aprokop** [comment]
I may have mussed something. Why is that expected, and how do we fix it?

**Comment by masterleinad** [comment]
Let me see what happens when I try.

**Comment by masterleinad** [comment]
https://github.com/masterleinad/ArborX/runs/702800116?check_suite_focus=true looks good but https://github.com/arborx/ArborX/runs/702801940?check_suite_focus=true doesn't. I was basically seeing before that if the check is only requested for the pull request and not for the branch in the fork that the check could not synchronize correctly. Apparently, this is still a problem if the pull request and the respective branch are part of different repositories.

**Pull request merged**
