### PR TITLE
Use Kokkos 3.4 for SYCL

### PR DESCRIPTION
**Pull request by masterleinad**
We should test with the new release and since there is a lot that has changed for for `SYCL`, this seems to be a good candidate.

### CODE REVIEW

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Looks like this also resolves the SYCL tests timing out. 
Note that I was seeing some warnings intermediately that were stemming from building a new `SYCL` compiler version.

**Review by dalg24 — APPROVED** [review]
Thank you for taking care of this

**Review by aprokop — APPROVED** [review]

**Comment by aprokop** [comment]
@masterleinad Please don't forget to update the Wiki's Testing page.

So the only SYCL version that worked was the one that was used in Kokkos? 

> Looks like this also resolves the SYCL tests timing out.

Fingers crossed, but it is not necessarily the case, they do pass sometimes.

**Comment by masterleinad** [comment]
> So the only SYCL version that worked was the one that was used in Kokkos?

Yes, CUDA support in SYCL is pretty brittle.

**Pull request merged**
