### PR TITLE
Drop extra parallel_reduce() when sorting objects in distributed tree

### PR DESCRIPTION
**Pull request by dalg24**
Following up on https://github.com/arborx/ArborX/pull/248#issuecomment-605071389

### CODE REVIEW

**Comment by aprokop** [comment]
Good catch! Why is this [WIP]?

**Comment by masterleinad** [comment]
It's not quite clear if this was ever intended to help with performance or not. At the moment, this function doesn't really show up in profiles but I will just run some profiling on this pull request to see if I spot any difference.

**Comment by masterleinad** [comment]
Just as expected, I don't see any significant difference between the two versions. Let's just get rid of it. We are optimizing for an unlikely case in the end.

**Comment by masterleinad** [comment]
I fixed the warning.

**Pull request merged**
