### PR TITLE
Replace Kokkos::ViewAllocateWithoutInitializing

### PR DESCRIPTION
**Pull request by masterleinad**
`Kokkos::ViewAllocateWithoutInitializing` should be deprecated soon.

### CODE REVIEW

**Comment by aprokop** [comment]
This is a bit early, but welcome. Lets work on merging the labels ones first, and then rebase this one on top of those.

**Comment by aprokop** [comment]
`Kokkos::view_alloc(Kokkos::WithoutInitializing, "label")` is a handful to write. How about we abbreviate it to `Kokkos::no_init("name")` with it defined as
```
namespace Kokkos {
auto no_init = [](std::string const& label) {
  return Kokkos::view_alloc(Kokkos::WithoutInitializing, label);
};
}
```
or similar?

**Comment by masterleinad** [comment]
I don't think that we should mess with an external namespace. I am fine with an abbreviation in `namespace ArborX`, though. For me, it's not necessary to really do it on the other hand.

**Comment by aprokop** [comment]
@dalg24 I thought you had thoughts on this. Please share.

**Comment by dalg24** [comment]
> @dalg24 I thought you had thoughts on this. Please share.

I mentioned we should consider providing free functions to create views
```C++
auto v = KokkosExt::makeWithoutInializing<Kokkos::View<T, P...>>(Args&&... args);
auto w = KokkosExt::make<Kokkos::View<T, P...>>(Args&&... args);

**Comment by aprokop** [comment]
> I mentioned we should consider providing free functions to create views

I don't know what to think of it. For regular views, I like using the standard way of constructing them, and see no benefit in introducing a free function. For uninitialized views, this may be helpful, but goes a weird way to do it.

What are the benefits of the free functions that I'm not seeing here?

**Pull request closed without merging**
