### PR TITLE
Fix Kokkos header includes

### PR DESCRIPTION
**Pull request by dalg24**
I had to resolve some Kokkos header includes issue in another project and scanned ours just our curiosity.
Here are a couple trivial fixes.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]

**Review by aprokop — APPROVED** [review]
LGTM. Any automated way of doing this?

**Comment by dalg24** [comment]
> Any automated way of doing this?

What do you mean automated?

**Comment by aprokop** [comment]
> What do you mean automated?

My understanding is that you simply grepped for the inclusion of specific files. I'm not sure what was the process of figuring out what to search for, or how to determine what the problem was.

**Comment by dalg24** [comment]
I did 
```
git grep "Kokkos_.*.hpp" | grep -v Kokkos_Core.hpp | grep -v Kokkos_Macros.hpp
examples/dbscan/ArborX_DBSCANVerification.hpp:#include <Kokkos_View.hpp>
examples/molecular_dynamics/example_molecular_dynamics.cpp:#include <Kokkos_Random.hpp>
src/details/ArborX_DetailsKokkosExtArithmeticTraits.hpp:#include <Kokkos_NumericTraits.hpp>
src/details/ArborX_DetailsKokkosExtDetectionIdiom.hpp:#include <Kokkos_DetectionIdiom.hpp>
src/details/ArborX_DetailsSortUtils.hpp:#include <Kokkos_Sort.hpp>
src/details/ArborX_KDOP.hpp:#include <Kokkos_Array.hpp>
test/boost_ext/KokkosPairComparison.hpp:#include <Kokkos_Pair.hpp>
test/tstHeapOperations.cpp:#include <Kokkos_Array.hpp>
test/tstQueryTreeIntersectsKDOP.cpp:#include <Kokkos_CopyViews.hpp>
```

**Comment by dalg24** [comment]
From there I opened `examples/dbscan/ArborX_DBSCANVerification.hpp` and immediately saw that it had multiple `Kokkos::parallel_reduce` calls so it needs to include the full `<Kokkos_Core.hpp>`.
Then I spotted the `<Kokkos_CopyViews.hpp>` include which I could see us on the Kokkos side make a "private" header in the future and looked at the unit test and judged we might as well include everything from Kokkos Core.

**Pull request merged**
