### PR TITLE
Fixup executable path when running tests

### PR DESCRIPTION
**Pull request by dalg24**
The changes using cmake generator expressions in the MPI tests are required when using the Ninja Multi-Config generator.

### CODE REVIEW

**Comment by aprokop** [comment]
Note to self.

### CMake add_test

The `COMMAND` argument works likes this:
```
    Specify the test command-line. If <command> specifies an executable target (created by [add_executable()](https://cmake.org/cmake/help/latest/command/add_executable.html#command:add_executable)) it will automatically be replaced by the location of the executable created at build time.

**Review by aprokop — APPROVED** [review]

**Comment by dalg24** [comment]
It seems to expand the path properly when it does `COMMAND <TargetName> <args>...` that's why I did not use a generator expression in that case

**Review by masterleinad — APPROVED** [review]

**Comment by aprokop** [comment]
> It seems to expand the path properly when it does `COMMAND <TargetName> <args>...` that's why I did not use a generator expression in that case

Yes, I double checked that too. As long as the proper target name is the first argument, it's fine.

**Comment by aprokop** [comment]
Two builds ran out of time (HIP, SYCL), ignoring.

**Pull request merged**
