### PR TITLE
Update arithmetic traits

### PR DESCRIPTION
**Pull request by dalg24**
* Rename Kokkos::ArithmeticTraits::{max -> finite_max}
* Add Kokkos::ArithmeticTraits::finite_min
* Add int and long long specializations of finite_{min,max}

I would like to use these in #646

### CODE REVIEW

**Review by aprokop — COMMENTED** [review]
Please provide a reference on the origin of the name, it's not in the C++ standard. Honestly, I don't see how this makes anything clearer.

**Comment by dalg24** [comment]
The goal is to transition to the facility in Kokkos and as you can see in the diff we were previously doing
```C++
template <class T>
using max = Kokkos::Experimental::finite_max<T>;
```
so the changes proposed align better.  I am introducing `finite_min` and the issue with `min()` from `std::numeric_limits` is that it has different meaning for integral types and for floating points.

As for the name, Kokkos implements the [new facility that is being proposed for C++23](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1841r3.pdf).  It is in `Kokkos::Experimental::` but the plan is to promote it when C++23 is released and we know it will not change.

**Comment by aprokop** [comment]
> As for the name, Kokkos implements the [new facility that is being proposed for C++23](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1841r3.pdf). It is in `Kokkos::Experimental::` but the plan is to promote it when C++23 is released and we know it will not change.

It was not clear from the paper, is `<numbers>` going to replace `<limits>`, and `finite_max` going to replace `max`?

**Review by aprokop — APPROVED** [review]

**Comment by dalg24** [comment]
It supersedes it but they will live side by side for the foreseeable future.

**Pull request merged**
