### PR TITLE
Integrate MST into the DBSCAN driver

### PR DESCRIPTION
**Pull request by aprokop**

### CODE REVIEW

**Comment by aprokop** [comment]
> This is fine. We will need to revisit later the subdirectory and executable name.

Yeah. I think we'll need to move the whole machinery about loading the data into a separate file. That would leave with just simple drivers for dbscan, hdbscan, mst, etc.

**Comment by aprokop** [comment]
Somehow, all these produce warnings:
```
view.extent(0) == bvh.size()
(int)view.extent(0) == bvh.size()
view.extent(0) == (int) bvh.size()
```
Does it mean that only `(int)view.extent(0) == (int)bvh.size()` will work?

**Comment by masterleinad** [comment]
> Does it mean that only `(int)view.extent(0) == (int)bvh.size()` will work?

IIRC `extent` is of type `View::size_type`(which is `signed` for `SYCL` and `unsigned` otherwise but we want all of them to switch to `signed` eventually). So casting the right-hand side to that should work.

**Comment by dalg24** [comment]
`Kokkos::View::extent(Integral) -> size_t` and `ArborX::BVH::size() -> MemorySpace::size_type` which depends on the backend you use.

**Comment by aprokop** [comment]
@dalg24 thanks for the help!

**Pull request merged**
