### PR TITLE
Reenable quality gates

### PR DESCRIPTION
**Pull request by masterleinad**
Let's try to figure out why this was giving unexpected failures/warnings.

### CODE REVIEW

**Comment by aprokop** [comment]
[tests passed]
retest this please

**Comment by aprokop** [comment]
retest this please

**Comment by aprokop** [comment]
Record: tests passed

**Comment by aprokop** [comment]
retest this please

**Comment by aprokop** [comment]
So we got a ton of warnings in the [latest build])https://cloud.cees.ornl.gov/jenkins-ci/job/ArborX/job/PR-211/1/). All are coming from boost. I thought `CMAKE_PREFIX_PATH` directories would have had `-isystem` added and thus should not have produced warnings. Is that not the case?

**Comment by dalg24** [comment]
Do these show in the actual build logs?

**Comment by masterleinad** [comment]
It looks like the come from biulding `boost` and not from building `ArborX`.

**Comment by masterleinad** [comment]
https://cloud.cees.ornl.gov/jenkins-ci/blue/rest/organizations/jenkins/pipelines/ArborX/branches/PR-211/runs/1/nodes/12/steps/56/log/?start=0

**Comment by aprokop** [comment]
> Do these show in the actual build logs?

I don't see them in the logs.

**Comment by masterleinad** [comment]
Building the `Docker` image creates them.

**Comment by aprokop** [comment]
@masterleinad Great point, did not notice that! So, we getting everything dumped into the log, and scripts are not smart to separate ArborX build from everything else.

**Pull request merged**
