### PR TITLE
Export CMake config

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by dalg24** [comment]
Closes #12 

Ready for review!

**Comment by Rombur** [comment]
This PR gives me warning from Boost that I don't have on master
```
[12/35] Building CXX object test/CMakeFiles/ArborX_DetailsTreeTraversal.exe.dir/tstDetailsTreeTraversal.cpp.o                                                       
../test/tstDetailsTreeTraversal.cpp:34: warning: "BOOST_TEST_MODULE" redefined                                                                                                                                     
 #define BOOST_TEST_MODULE Containers                                                                                                          
                                                                                                                                                                                                                   
../test/tstDetailsTreeTraversal.cpp:28: note: this is the location of the previous definition                                                                                                                      
 #define BOOST_TEST_MODULE DetailsTreeTraversal                                        
                                                                                                                                                                                                                   
../test/tstDetailsTreeTraversal.cpp:160: warning: "BOOST_TEST_MODULE" redefined
 #define BOOST_TEST_MODULE ContainerAdaptors                       
                                                                                                                  
../test/tstDetailsTreeTraversal.cpp:34: note: this is the location of the previous definition
 #define BOOST_TEST_MODULE Containers                        
                                                                      
../test/tstDetailsTreeTraversal.cpp:229: warning: "BOOST_TEST_MODULE" redefined
 #define BOOST_TEST_MODULE HeapOperations                     
                           
../test/tstDetailsTreeTraversal.cpp:160: note: this is the location of the previous definition
 #define BOOST_TEST_MODULE ContainerAdaptors               
                                                                                                   
../test/tstDetailsTreeTraversal.cpp:408: warning: "BOOST_TEST_MODULE" redefined
 #define BOOST_TEST_MODULE PriorityQueue                                                                                                                                                                                                                                                                                                                                                                                              ../test/tstDetailsTreeTraversal.cpp:229: note: this is the location of the previous definition
 #define BOOST_TEST_MODULE HeapOperations    
```

**Comment by dalg24** [comment]
> This PR gives me warning from Boost that I don't have on master

These have been fixed in #20

**Comment by dalg24** [comment]
@masterleinad please review this one and coordinate with #33

**Comment by dalg24** [comment]
Fixed merge that went wrong...

**Comment by masterleinad** [comment]
The first commits look good to me. I had to avoid adding `src` as `CMake` subdirectory to be able to configure, though. I also pushed a commit with minimum requirements for `Boost` and `CMake`.

**Comment by masterleinad** [comment]
We can merge if you are fine with my changes.

**Comment by dalg24** [comment]
@masterleinad Please open an issue to capture the discussion on the minimum requirement for CMake and Boost

This will be useful when we add instructions for installing ArborX

**Pull request merged**
