### PR TITLE
Remove brute force example

### PR DESCRIPTION
**Pull request by aprokop**
As we are moving the comparison to bvh in #731, this no longer is useful as an example.

Drive-by change: alphabetically order example directories inside `examples/CMakeLists.txt`.

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
Too much of a simplification IMO
Would need to print something.  Also does not hurt to have a BVH and show the API is the same and you find the same answer

**Comment by aprokop** [comment]
> Would need to print something. Also does not hurt to have a BVH and show the API is the same and you find the same answer

Depends on what we are trying to show. We have `examples/simple_intersection` as to demonstrate of how to use BVH. I don't see a need for BVH here. I do agree with with doing something with the results. Printing is certainly an option, though I wonder how useful that is.

**Comment by masterleinad** [comment]
I agree that examples should print something. It could be listing all matches for every predicate for instance.

**Comment by aprokop** [comment]
Now prints out the percentage of collided queries out of all possible.

**Comment by aprokop** [comment]
Resolved conflicts with master. This is ready for review.

**Review by anagainaru — COMMENTED** [review]
In the current format (no comparison to BVH and no timing information), I really don't think it's worth having this example. You could just add a comment in the `examples/simple_intersection` or in some documentation to show that brute force and bvh can be interchanged.
 
E.g. changing the line from `examples/simple_intersection`:
```
    ArborX::BVH<MemorySpace> const tree(execution_space, boxes);
```
to `  ArborX::BruteForce<MemorySpace>` would be enough.

**Comment by dalg24** [comment]
I think we should keep an example that shows how both indexes can be used.

**Comment by aprokop** [comment]
OK, I don't know what to do with it at the moment.

**Pull request closed without merging**
