### PR TITLE
Allow including distributed tree files when MPI support is disabled

### PR DESCRIPTION
**Pull request by masterleinad**
Addressing:
> I don't necessarily see something wrong with including headers that include the distributed implementation even if ArborX has been configured without MPI support.
I would also argue that not all the files that implement the distributed implementation include `mpi.h` directly (which was the reason for the previous commit to fail).

_Originally posted by @masterleinad in https://github.com/arborx/ArborX/pull/396#discussion_r496295475_

### CODE REVIEW

**Comment by aprokop** [comment]
I don't know the reason behind the original implementation, and have no opinion on the matter, so I defer to @dalg24.

**Review by dalg24 — COMMENTED** [review]
First of you forgot `ArborX_DetailsDistributedTreeImpl.hpp`.

Second I don't see much value added by this PR.

You are trading a "`<mpi.h>` include" for "`<ArborX_Config.hpp>` include and header guards" required in all files that use MPI.  You reduce complexity in the header self containment unit test at the cost of more tests.

**Comment by masterleinad** [comment]
> You are trading a "`<mpi.h>` include" for "`<ArborX_Config.hpp>` include and header guards" required in all files that use MPI. You reduce complexity in the header self containment unit test at the cost of more tests.

This is not what I justified the PR in https://github.com/arborx/ArborX/pull/397#issue-494496745 with. For me, it's rather that it should be valid to include these files even if you don't use MPI functionality. 
I am fine with only testing public-facing headers in the first place to reduce complexity.

**Comment by masterleinad** [comment]
This isn't popular so let's close.

**Pull request closed without merging**
