### PR TITLE
#745: Pass through execution space argument in sorting

### LINKED ISSUE #745: Kokkos BinSort now provides execution-space overloads
This FIXME comment can now be addressed:
https://github.com/arborx/ArborX/blob/48ef73cd3f87c35ee30cfdd84cbdde3509c0af5a/src/details/ArborX_DetailsSortUtils.hpp#L119

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes #745

### CODE REVIEW

**Comment by aprokop** [comment]
@PhilMiller Thank you for the contribution. What version of Kokkos did it first appear in?

**Comment by PhilMiller** [comment]
I was introduced in 3.5

**Comment by aprokop** [comment]
Interesting error in `CUDA-11.5.2-NVCC` build:
```
/opt/kokkos/include/impl/Kokkos_FunctorAnalysis.hpp(119): error: static assertion failed with "Execution Policy and Functor execution space must match"
  detected during:
   instantiation of class "Kokkos::Impl::FunctorAnalysis<PatternInterface, Policy, Functor> [with
PatternInterface=Kokkos::Impl::FunctorPatternInterface::SCAN, 
Policy=Kokkos::RangePolicy<Kokkos::Serial::execution_space, 
Kokkos::BinSort<
  Kokkos::View<unsigned long long *, Kokkos::Serial::memory_space>, 
  Kokkos::BinOp1D<Kokkos::View<unsigned long long *, Kokkos::Serial::memory_space>>, 
  Kokkos::Device<Kokkos::HostSpace::execution_space, 
  Kokkos::HostSpace::memory_space>, unsigned int>::bin_offset_tag
>, 
Functor=Kokkos::BinSort<
  Kokkos::View<unsigned long long *, Kokkos::Serial::memory_space>,
  Kokkos::BinOp1D<Kokkos::View<unsigned long long *, Kokkos::Serial::memory_space>>, 
  Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::HostSpace::memory_space>, unsigned int>
]" 
```

**Comment by PhilMiller** [comment]
That's a bug that was fixed in Kokkos, https://github.com/kokkos/kokkos/pull/4919

It now checks accessibility, rather than equality.

The fix is only in 3.7, which is just coming out, though.

**Comment by aprokop** [comment]
But I think in our case it they should be equal, as they are used within the same function.

**Comment by PhilMiller** [comment]
Since this is kind of a drive-by effort from me, as an aside to work I'm supposed to be doing on Kokkos sorting, I think I'll leave this as "re-assess when ArborX requires Kokkos 3.7", if that's OK with you

**Comment by PhilMiller** [comment]
The underlying issue that prompted that PR is exactly what we're seeing here:
https://github.com/kokkos/kokkos/issues/4891

**Comment by aprokop** [comment]
> Since this is kind of a drive-by effort from me, as an aside to work I'm supposed to be doing on Kokkos sorting, I think I'll leave this as "re-assess when ArborX requires Kokkos 3.7", if that's OK with you

Yeah, that's fine. And you are right. I think this piece of code is what makes it happen in testing:
```
BOOST_AUTO_TEST_CASE_TEMPLATE(sort_objects, DeviceType, ARBORX_DEVICE_TYPES)
{
  using ExecutionSpace = typename DeviceType::execution_space;
  ExecutionSpace space{};

  std::vector<int> values = {...};
  Kokkos::View<int *, Kokkos::HostSpace> host_view("data", values.size());   std::copy(values.begin(), values.end(), host_view.data());
  auto device_view = Kokkos::create_mirror_view_and_copy(space, host_view);
  auto device_permutation = ArborX::Details::sortObjects(space, device_view);
```
I think when run with `Serial`, the device type for the `host_view` is using `Kokkos::HostSpace::execution_space`, mismatching `ExecutionSpace`.

**Review by aprokop — APPROVED** [review]

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
