### PR TITLE
Silence warnings from building SYCL image

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by masterleinad** [comment]
I'm fine with the changes here but the CI gives weird results:
```
	  1 - ArborX_DetailsUtils_Test (Subprocess aborted)
	  3 - ArborX_QueryTree_Test (Subprocess aborted)
	  4 - ArborX_DetailsTreeConstruction_Test (Subprocess aborted)
	  6 - ArborX_DetailsBatchedQueries_Test (Subprocess aborted)
	  7 - ArborX_DetailsCrsGraphWrapperImpl_Test (Subprocess aborted)
	  8 - ArborX_Clustering_Test (Subprocess aborted)
	  9 - ArborX_DistributedTree_Test (Failed)
	 10 - ArborX_DetailsDistributedTreeImpl_Test (Failed)
	 13 - ArborX_Callback_Example (Subprocess aborted)
	 14 - ArborX_Intersection_Example (Subprocess aborted)
	 15 - ArborX_MolecularDynamics_Example (Subprocess aborted)
	 17 - ArborX_DBSCAN_Example (Subprocess aborted)
	 18 - ArborX_RayTracing_Example (Subprocess aborted)
	 19 - ArborX_BruteForce_Example (Subprocess aborted)
	 20 - ArborX_BoundingVolumeHierarchy_Benchmark (Subprocess aborted)
	 21 - ArborX_ExecutionSpaces_Benchmark (Subprocess aborted)
	 22 - ArborX_DistributedTree_Benchmark (Failed)
```

**Comment by aprokop** [comment]
After retesting, the builds passed, but still a ton of warnings. Not sure if they are the ones this patch was supposed to fix, though.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by dalg24** [comment]
Yes I have seen that one but did not bother looking into it.
You chose whether we merge or close.  There is no point keeping open longer.

**Comment by dalg24** [comment]
Ping

**Review by masterleinad — APPROVED** [review]
Someone else should have a look and approve.

**Pull request merged**
