### PR TITLE
Do not build benchmark tests when building container

### PR DESCRIPTION
**Pull request by aprokop**
It also tries to find gtest when tests are enabled, which fails on
CADES, for example.

### CODE REVIEW

**Comment by dalg24** [comment]
> It also tries to find gtest when tests are enabled, which fails on
> CADES, for example.

I don't understand the issue.  We do pull the google test.  Also how is the failure related to the Dockerfile?

**Comment by aprokop** [comment]
> I don't understand the issue. We do pull the google test. Also how is the failure related to the Dockerfile?

This is unrelated to docker container per se. However, `BENCHMARK_ENABLE_TESTING` is `ON` by default, and it builds several tests when building benchmark. We don't need them, so might as well disable.

The failure was on CADES, which does not have gtest. The only reason I mentioned that is that is what lead to this discovery.

**Comment by aprokop** [comment]
Actually, why do we need google test clone? We should probably remove that too, that's unnecessary.

**Comment by aprokop** [comment]
retest this please

**Pull request merged**
