### PR TITLE
Upgrade Boost from 1.67.0 to 1.71.0 in CI/dev image

### PR DESCRIPTION
**Pull request by dalg24**
Related to #168

### CODE REVIEW

**Comment by aprokop** [comment]
This was just a check pull request, no need to keep it open.

**Comment by dalg24** [comment]
Still does not liking NVCC :/

**Comment by aprokop** [comment]
Yeah, I expected that. In the boost upstream PR, I tried 1.72 with proposed patch and it did not work. I'm not sure that 1.73 is going to be any better.

**Comment by aprokop** [comment]
If you can write a reproducer, we can submit it to the upstream thread to facilitate the fix.

**Pull request closed without merging**
