### PR TITLE
Enable compiler cache in Jenkins CI

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by dalg24** [comment]
> Neat, have you timed the improvement?

2min -> 10sec to rebuild the same thing after removing the build directory

**Comment by aprokop** [comment]
Have you set up the ccache configuration, stating the max amount of space it is allowed to take?

**Comment by dalg24** [comment]
> Have you set up the ccache configuration, stating the max amount of space it is allowed to take?

I have not

**Comment by dalg24** [comment]
> > Have you set up the ccache configuration, stating the max amount of space it is allowed to take?
> 
> I have not

The default is 5G.  We can use the env variable `CCACHE_MAXSIZE` to control it.  What value do you suggest we specify?

Also I realize now it would not be a bad idea to print the cache statistics at the end of the build script.  What do you think?

**Comment by aprokop** [comment]
> Also I realize now it would not be a bad idea to print the cache statistics at the end of the build script. What do you think?

yes!

**Comment by dalg24** [comment]
Done

**Comment by dalg24** [comment]
[build 7](https://cloud.cees.ornl.gov/jenkins-ci/job/ArborX/7/) 4min12sec 
vs 
[build 10](https://cloud.cees.ornl.gov/jenkins-ci/job/ArborX/10/) 1min16sec

**Pull request merged**
