### PR TITLE
Reorganize geometry/

### PR DESCRIPTION
**Pull request by aprokop**
Reorganize geometry files. The goal is to not make `ArborX_GeometryAlgorithms.hpp` a dump that we just put all stuff in. Instead of a single `ArborX_GeometryAlgorithms.hpp`, we now have
```
ArborX_GeometryAlgorithms.hpp
ArborX_GeometryCentroid.hpp
ArborX_GeometryConvert.hpp
ArborX_GeometryDistance.hpp
ArborX_GeometryEquals.hpp
ArborX_GeometryExpand.hpp
ArborX_GeometryIntersects.hpp
ArborX_GeometryValid.hpp
```

Did not touch `ArborX_Ray.hpp` as it needs a ton more work.

I could split header files further, like the following, but not sure whether I should do it right now.
```
ArborX_GeometryDistanceBoxBox.hpp
ArborX_GeometryDistanceBoxSphere.hpp
ArborX_GeometryDistancePointBox.hpp
ArborX_GeometryDistancePointPoint.hpp
ArborX_GeometryDistancePointSphere.hpp
ArborX_GeometryDistancePointTriangle.hpp
ArborX_GeometryExpandBoxBox.hpp
ArborX_GeometryExpandBoxKDOP.hpp
ArborX_GeometryExpandBoxPoint.hpp
ArborX_GeometryExpandBoxSphere.hpp
ArborX_GeometryExpandKDOPKDOP.hpp
ArborX_GeometryExpandKDOPPoint.hpp
ArborX_GeometryIntersectsBoxBox.hpp
ArborX_GeometryIntersectsBoxKDOP.hpp
ArborX_GeometryIntersectsBoxTriangle.hpp
ArborX_GeometryIntersectsKDOPKDOP.hpp
ArborX_GeometryIntersectsPointBox.hpp
ArborX_GeometryIntersectsPointKDOP.hpp
ArborX_GeometryIntersectsPointSphere.hpp
ArborX_GeometryIntersectsPointTriangle.hpp
ArborX_GeometryIntersectsSphereBox.hpp
```

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
I don't like the Geometry prefix in the file names

**Comment by aprokop** [comment]
> I don't like the Geometry prefix in the file names

I find that without it the names are too generic.

**Comment by dalg24** [comment]
> > I don't like the Geometry prefix in the file names
> 
> I find that without it the names are too generic.

You could 1/ add an algorithms/ subdirectory, 2/ consider having to name the "root" dir in which case these become `#include <geometry/algorithms/ArborX_Centroid.hpp`

**Comment by aprokop** [comment]
> You could 1/ add an algorithms/ subdirectory, 2/ consider having to name the "root" dir in which case these become `#include <geometry/algorithms/ArborX_Centroid.hpp`

While I do understand your desire to not have `Geometry` in the filename, 
2/ would make trivial things, like including a box, require `#include <geometry/ArborX_Box.hpp>`. This seems like a lot. Without 2, however, 1/ does not make any difference.

Boost.Geometry is able to avoid that because it is a part of the Boost ecosystem, which means one has to type `boost/<package_name>` anyway. In that case, `algorithms` makes sense as they would result in `boost/test/algorithms/blah.hpp`.

**Comment by aprokop** [comment]
- Got rid of `ArborX_GeometryAlgorithms.hpp`
- Moved `geometry/detail` -> `geometry/algorithms`
- Removed `Geometry` from filenames (the only exception is `ArborX_GeometryTraits.hpp`)
- Changed all files to now include `algorithms/ArborX_Blah.hpp` for individual algorithms they need

**Review by dalg24 — APPROVED** [review]
Sure

**Comment by aprokop** [comment]
CI failures are unrelated (CUDA GPU disappearing).

**Pull request merged**
