### PR TITLE
Fix an issue in the query test using manufactured solution

### PR DESCRIPTION
**Pull request by aprokop**
When increasing the problem size from 11^3 to 51^3 in the manufactured
solution test, it failed:
```
../test/tstQueryTreeManufacturedSolution.cpp(254):
error: in "ManufacturedSolution/structured_grid<TreeExecutionAndMemorySpaces<ArborX__BoundingVolumeHierarchy, Kokkos__Device<Kokkos__Serial, Kokkos__HostSpace> >>":
check query(ExecutionSpace{}, tree, queries) == (make_reference_solution(indices_ref, offset_ref)) has failed
Mismatch at position 107186: ( 85094 87695 ) != ( 85094 ).
Mismatch at position 111824: ( 122546 125147 ) != ( 122546 ).
```
A query could find multiple points if the query box was aligned with one
of the grid lines, or close to it.

This patch changes the way we generate the random queries to make sure
each query does not get too close to a grid line, thus guaranteeing a
single result.

### CODE REVIEW

**Review by dalg24 — COMMENTED** [review]
The code proposed does not use `Lx`, `Ly` and `Lz` so the domain over which we generate points changes.  This does not look right.

**Comment by aprokop** [comment]
> The code proposed does not use `Lx`, `Ly` and `Lz` so the domain over which we generate points changes. This does not look right.

No. We randomly select an index `(i, j, k)` within `[0, nx-1]x[0, ny-1]x[0,nz-1]`. It is then multiplied by `hx`/`hy`/`hz` spanning the full domain. If one wants to be pedantic, the domain over which the centers of the query boxes are generated increased slightly in each dimension, e.g., for `x` it went from`[0, Lx]` to `[-0.45hx, Lx+0.45hx]`.

**Comment by dalg24** [comment]
> > The code proposed does not use `Lx`, `Ly` and `Lz` so the domain over which we generate points changes. This does not look right.
> 
> No. We randomly select an index `(i, j, k)` within `[0, nx-1]x[0, ny-1]x[0,nz-1]`. It is then multiplied by `hx`/`hy`/`hz` spanning the full domain. If one wants to be pedantic, the domain over which the centers of the query boxes are generated increased slightly in each dimension, e.g., for `x` it went from`[0, Lx]` to `[-0.45hx, Lx+0.45hx]`.

My bad, I missed the `hx` scaling factor

**Comment by aprokop** [comment]
How do we move forward with this? If you have an alternative solution, feel free to contribute, but if not, can we just merge it?

**Comment by dalg24** [comment]
Would you remind me if you saw failures when generating single precision floating point numbers?

**Comment by aprokop** [comment]
The following patch still fails on master (83dfeca3):
```diff
--- a/test/tstQueryTreeManufacturedSolution.cpp
+++ b/test/tstQueryTreeManufacturedSolution.cpp
@@ -55,14 +55,14 @@ BOOST_AUTO_TEST_CASE_TEMPLATE(structured_grid, TreeTypeTraits,
   float Lx = 100.0;
   float Ly = 100.0;
   float Lz = 100.0;
-  int nx = 11;
-  int ny = 11;
-  int nz = 11;
+  int nx = 101;
+  int ny = 101;
+  int nz = 101;
   int n = nx * ny * nz;
   float hx = Lx / (nx - 1);
   float hy = Ly / (ny - 1);
   float hz = Lz / (nz - 1);

   std::function<int(int, int, int)> ind = [nx, ny](int i, int j, int k) {
     return i + j * nx + k * (nx * ny);
   };
@@ -223,17 +226,17 @@ BOOST_AUTO_TEST_CASE_TEMPLATE(structured_grid, TreeTypeTraits,
   //  o       o       o   j-1
   //
   std::default_random_engine generator;
-  std::uniform_real_distribution<double> distribution_x(0.0, Lz);
-  std::uniform_real_distribution<double> distribution_y(0.0, Ly);
-  std::uniform_real_distribution<double> distribution_z(0.0, Lz);
+  std::uniform_real_distribution<float> distribution_x(0.0, Lz);
+  std::uniform_real_distribution<float> distribution_y(0.0, Ly);
+  std::uniform_real_distribution<float> distribution_z(0.0, Lz);

   std::iota(offset_ref.begin(), offset_ref.end(), 0);
   indices_ref.resize(n);
   for (int l = 0; l < n; ++l)
   {
-    double x = distribution_x(generator);
-    double y = distribution_y(generator);
-    double z = distribution_z(generator);
+    float x = distribution_x(generator);
+    float y = distribution_y(generator);
+    float z = distribution_z(generator);
     bounding_boxes_host(l) = {{{x - 0.5 * hx, y - 0.5 * hy, z - 0.5 * hz}},
                               {{x + 0.5 * hx, y + 0.5 * hy, z + 0.5 * hz}}};
```
with
```
$ ./ArborX_QueryTree.exe -t */structured_grid*
Running 8 test cases...
../test/tstQueryTreeManufacturedSolution.cpp(257): error: in "ManufacturedSolution/structured_grid<TreeExecutionAndMemorySpaces<ArborX__BoundingVolumeHierarchy, Kokkos__Device<Kokkos__Cuda, Kokkos__CudaSpace> >>": check query(ExecutionSpace{}, tree, queries) == (make_reference_solution(indices_ref, offset_ref)) has failed
Mismatch at position 33936: ( 303404 303505 ) != ( 303505 ).
Mismatch at position 328136: ( 148549 148550 ) != ( 148550 ).
Mismatch at position 353304: ( 314674 324875 ) != ( 324875 ).
Mismatch at position 362271: ( 695117 705318 ) != ( 705318 ).
Mismatch at position 491367: ( 503405 513606 ) != ( 513606 ).
Mismatch at position 608860: ( 135734 135835 ) != ( 135835 ).
Mismatch at position 634586: ( 773122 773123 ) != ( 773123 ).
Mismatch at position 781924: ( 7230 7331 ) != ( 7331 ).
Mismatch at position 787210: ( 241167 241168 ) != ( 241168 ).
Mismatch at position 796486: ( 321403 321404 ) != ( 321404 ).
Mismatch at position 848403: ( 440933 451134 ) != ( 451134 ).
```

**Review by dalg24 — APPROVED** [review]
Add a comment to saying the generation is a bit convoluted to avoid that box centroid falls on any of the lattice planes in which case we would get more than one collision.

**Pull request merged**
