### PR TITLE
Update HIP CI build ROCm 4.2 -> 5.0

### PR DESCRIPTION
**Pull request by dalg24**
CMake 3.18.5 -> 3.22.4
Boost 1.72.0 -> 1.79.0
Google Benmchark 1.5.0 -> 1.6.1

### CODE REVIEW

**Comment by aprokop** [comment]
Expired CMake key.

**Comment by dalg24** [comment]
No that is not the issue.  See kokkos/kokkos#4601

**Comment by aprokop** [comment]
Starting from 1.76.0, the place we download boost from, e.g., [1.79.0](https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/) do not carry `.asc` signature files.

**Comment by aprokop** [comment]
retest this please

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
Retest this please

**Review by aprokop — APPROVED** [review]

**Comment by dalg24** [comment]
Retest this please

**Comment by dalg24** [comment]
I wasn't able to reproduce the HIP failure (cmake not finding MPI)
Would someone else be able to try as well?

**Comment by aprokop** [comment]
Hmm, HIP took 40 minutes to build. Wonder if it's related to #652. In the previous HIP 4.2 test build we had
```
--amdgpu-target=gfx908 -xhip --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx908
```
The new 5.0 test build has
```
--amdgpu-target=gfx906 -x hip --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx908 --offload-arch=gfx90a --offload-arch=gfx1030
```

**Comment by aprokop** [comment]
With building just one target, the build now takes about 15 minutes. Still longer than it used to be, but it's acceptable.

**Review by aprokop — APPROVED** [review]

**Pull request merged**
