### PR TITLE
[WIP] Try recordIssues separately

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by masterleinad** [comment]
This seems to work even if it is not super.

**Comment by aprokop** [comment]
> This seems to work even if it is not super nice.

Can you please summarize what you did, and what is not nice about it?

**Comment by dalg24** [comment]
How did you ensure that the images were re-built and not used from the cache?

**Comment by masterleinad** [comment]
I just copied all the checks to every build. That required me to give them separate `ids` and now we have 20 reports from the plugin (https://cloud.cees.ornl.gov/jenkins-ci/job/ArborX/job/PR-212/7/) where most of them are likely multiply redundant.

**Comment by masterleinad** [comment]
> How did you ensure that the images were re-built and not used from the cache?

I didn't. AFAICT, the reports are local to the stages, but I can try to force rebuilding all the images by some silly change.

**Comment by dalg24** [comment]
> > How did you ensure that the images were re-built and not used from the cache?
> 
> I didn't. AFAICT, the reports are local to the stages, but I can try to force rebuilding all the images by some silly change.

Use `--no-cache`

**Comment by masterleinad** [comment]
Hmmm... Yes, doesn't work.

**Pull request closed without merging**
