### PR TITLE
Add gcc-5 tester

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Retest this please.

**Comment by masterleinad** [comment]
Not sure what the problem is here with the `gcc-5` tester. For some reason, the distributed tests time out, but I can run them successfully manually locally.
Also note that I don't see the errors @Rombur was reporting in https://github.com/ORNL-CEES/DataTransferKit/pull/563.

**Comment by aprokop** [comment]
Why do we need this PR?

**Comment by masterleinad** [comment]
IIRC, @Rombur was reporting some problems with older compilers in `DTK`, in particular, `gcc-5`. I don't feel strongly about this pull request.

**Pull request closed without merging**
