### PR TITLE
Add build compiling CUDA with Clang in CI

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by masterleinad** [comment]
Just replacing `BOOST_TEST` with `assert` resolves the build problems. Admittedly, this is not a nice solution but at least works.

**Comment by masterleinad** [comment]
I am not quite sure why `CUDA-9.2-Clang` is still failing. Maybe related to `boost` not being built with `toolset=clang`?

**Comment by aprokop** [comment]
If replacing `BOOST_TEST` the only way, I would rather live without clang :/

**Comment by masterleinad** [comment]
Is there a problem with `continuous-integration/jenkins/pr-merge`?

**Comment by dalg24** [comment]
Not sure.  Try to re-trigger the build

**Comment by masterleinad** [comment]
retest this please

**Comment by masterleinad** [comment]
Hmm... seems like `continuous-integration/jenkins/pr-merge` is still not working correctly here.

**Comment by masterleinad** [comment]
Superseded by #93.

**Pull request closed without merging**
