### PR TITLE
Fix ambiguity in queryDispatch() overload resolution

### PR DESCRIPTION
**Pull request by dalg24**
Reported by @sslattery 
Problem was introduced in #271

### CODE REVIEW

**Comment by aprokop** [comment]
Can you please provide a bit more details? After staring at it for couple minutes, I don't see any difference.

**Comment by sslattery** [comment]
I was getting template deduction ambiguity errors on Summit and another machine when `nvcc` was being used. For the fix, it seems explicitly declaring parameters on some overloads as `Kokkos::View` allowed the deduction to proceed. We also tried an `enable_if` strategy with `is_view` that worked but this one is more clear I think.

**Comment by aprokop** [comment]
@sslattery Which compilers did you use on Summit? I have not experienced this issue when using gcc-7.4.0.

**Comment by sslattery** [comment]
```
> module list

Currently Loaded Modules:
  1) tmux/2.2   2) gcc/7.4.0   3) cuda/10.1.243   4) spectrum-mpi/10.3.1.2-20200121   5) cmake/3.15.2   6) git/2.20.1   7) hypre/2.13.0   8) fftw/3.3.8   9) boost/1.66.0
```

**Comment by sslattery** [comment]
Note that this error occurred when I defined my own callback in my application.

**Comment by dalg24** [comment]
He defined a custom callback with nearest predicates

**Comment by aprokop** [comment]
> I was getting template deduction ambiguity errors on Summit and another machine when `nvcc` was being used. For the fix, it seems explicitly declaring parameters on some overloads as `Kokkos::View` allowed the deduction to proceed. We also tried an `enable_if` strategy with `is_view` that worked but this one is more clear I think.

That's really weird. No explanation for this behavior? Is the behavior different with newer compilers (I think Summit has gcc-9 available).

**Comment by sslattery** [comment]
I also got this error with gcc-8 on CADES

**Comment by masterleinad** [comment]
Is there a minimal (stand-alone, i.e., only using `ArborX`) for the original error somewhere?

**Comment by sslattery** [comment]
I'll work on making a simple reproducer

**Comment by dalg24** [comment]
Retest this please

**Comment by sslattery** [comment]
[tstArborXCallback.hpp.txt](https://github.com/arborx/ArborX/files/4581129/tstArborXCallback.hpp.txt)

Simple reproducer. Written in Gtest framework but should be simple to convert as nothing is checked.

**Comment by masterleinad** [comment]
> Simple reproducer. Written in Gtest framework but should be simple to convert as nothing is checked.

Thanks!

**Pull request merged**
