### PR TITLE
Update check_format_cpp.sh script

### PR DESCRIPTION
**Pull request by aprokop**
- Provide an option to exclude files from consideration

### CODE REVIEW

**Comment by aprokop** [comment]
Squashed the commits, added empty `.clang-format-ignore`.

**Comment by aprokop** [comment]
Retest this please

**Comment by dalg24** [comment]
> Squashed the commits, added empty `.clang-format-ignore`.

So the file needs to exist after all?

**Comment by aprokop** [comment]
> So the file needs to exist after all?

Yes. Otherwise it always passes with the following output:
```shell
$ CLANG_FORMAT_EXE="clang-format-7" scripts/check_format_cpp.sh 
grep: .clang-format-ignore: No such file or directory
OK
```

**Pull request merged**
