### PR TITLE
Enable C++14 when building Kokkos in automated CI builds on Jenkins

### PR DESCRIPTION
**Pull request by dalg24**
We require C++14 standard but we rely on Kokkos to get the proper compiler flags.
This PR ensures that the `-std=c++14` flag will be present on the compile line in the automated builds on Jenkins.

### CODE REVIEW

**Comment by dalg24** [comment]
To be clear this PR does not attempt to solve the problem with are having with Kokkos and CMake regarding the proper way of setting the C++ standard.  I realize now the original title was misleading.

**Comment by masterleinad** [comment]
Would you mind to actually test that this works by using `std::make_unique` in `examples/distributed_tree_driver/distributed_tree_driver.cpp`?

**Comment by dalg24** [comment]
> Would you mind to actually test that this works by using `std::make_unique` in `examples/distributed_tree_driver/distributed_tree_driver.cpp`?

Done.

**Comment by masterleinad** [comment]
:smile:

**Pull request merged**
