### PR TITLE
Allow ordered spatial predicates in the distributed tree

### PR DESCRIPTION
**Pull request by aprokop**
This PR introduces ordered traversal in the distributed settings.

# Motivation

Thermal radiation using raytracing. Instead of spitting out all the intersections, we process them on the fly accumulating information within a rank.

# Semantics

I would like to have a discussion on what it actually means. In a distributed setting we can only guarantee the ordered traversal within a rank, but not among the ranks as the intersected ranks will be processed in parallel.

In addition, imagine a situation where the rank bounding boxes overlap, and the actual rank subdomain are non-convex. We can't truly perform a global ordered traversal in that case.

The only case where we can guarantee ordered results would be the case where subdomain boxes do not overlap. But I think this is already good.

### CODE REVIEW

**Comment by aprokop** [comment]
I have not put a test yet as we need to agree on the semantics first.

**Comment by Rombur** [comment]
> I would like to have a discussion on what it actually means. In a distributed setting we can only guarantee the ordered traversal within a rank, but not among the ranks as the intersected ranks will be processed in parallel.

We should do a reduce on the minimum intersection distance once the search is done.

**Comment by aprokop** [comment]
> We should do a reduce on the minimum intersection distance once the search is done.

I'm not sure I understand. Can you please elaborate?

**Comment by Rombur** [comment]
If I understood correctly what you are saying we have multiple processors that will report a first hit of the ray.  To get a single hit, we need to find the hit with the smallest distance to the origin of the ray along the ray direction and filter out the other ones. So we should a reduce `min` on the results and keep the one that matches the `min`.

**Comment by aprokop** [comment]
@Rombur I'm not sure why you are talking about the first hit. If we were talking only about the one nearest thing, that would be one thing. But we are talking about processing all the intersections, but in order. However, it would be impossible to do in the distributed setting. Imagine non-convex subdomains, or not simply connected, in 1D. Lets say `| 0 | 1 | 0 | 1 | 0 | 1 |` are MPI ranks of subdomains that a ray intersects. What does it mean to have ordered traversal in this case?

**Pull request closed without merging**
