### PR TITLE
Build PGI image live

### PR DESCRIPTION
**Pull request by masterleinad**
Depends on #93. The first commit summarizes all the changes in #93 and should vanish as soon as we rebase. The actual changes are in the second commit where we build the PGI image live instead of reloading a prebuilt one (analogously to what we do for the other CI configurations).

### CODE REVIEW

**Comment by masterleinad** [comment]
I dropped the first commit.

**Comment by masterleinad** [comment]
Can we move forward here?

**Comment by masterleinad** [comment]
I would appreciate if we can move forward here.

**Comment by aprokop** [comment]
I have no thoughts on this other than I don't understand why we need this or what users of this are.

**Comment by masterleinad** [comment]
This allows being able to test with other `Kokkos` commits (see #236) and we don't need to maintain images. With this pull request, we treat `PGI` the same as the other compilers.

**Pull request merged**
