### PR TITLE
Add nightly HIP build with the latest ROCm release

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by aprokop** [comment]
Seems to work.

**Comment by aprokop** [comment]
What's the next step here? Add it to nightly? Or was it simply for testing whether it works?

**Comment by dalg24** [comment]
> What's the next step here? Add it to nightly? Or was it simply for testing whether it works?

I would have preferred if I could make it work without `hipcc`

**Comment by dalg24** [comment]
Giving up on making it work with amdclang++ as the cxx compiler for now.

**Comment by aprokop** [comment]
> Giving up on making it work with amdclang++ as the cxx compiler for now.

Meaning you want to merge it as is?

**Review by aprokop — APPROVED** [review]

**Comment by dalg24** [comment]
Yes

**Comment by aprokop** [comment]
We should probably introduce a `Continuous` section to our Testing page in the wiki.

**Pull request merged**
