### PR TITLE
Remove unusual comment style

### PR DESCRIPTION
**Pull request by aprokop**
This commenting style has been bothering me for a while. I don't see how it helps, and find it extremely distracting.

### CODE REVIEW

**Comment by aprokop** [comment]
Please review.

**Comment by dalg24** [comment]
> Please review.

Did you measure performance?

**Comment by aprokop** [comment]
> Did you measure performance?

Yes, it increased my performance.

**Comment by dalg24** [comment]
Sure

**Comment by aprokop** [comment]
I added comments that hopefully describe the situation in sufficient details.

**Pull request merged**
