### PR TITLE
Update version to 1.7 dev

### PR DESCRIPTION
**Pull request by aprokop**
While I could have done 1.7, I think it's pretty safe to say that our next release is going to be 2.0.

### CODE REVIEW

**Comment by dalg24** [comment]
I recommend we stick to 1.7 dev and flip it later right before we merge breaking changes in

**Comment by dalg24** [comment]
(not feeling too strongly about it though)

**Comment by aprokop** [comment]
> I recommend we stick to 1.7 dev and flip it later right before we merge breaking changes in

I'm sure we'll forget to flip the version until the release, but whatever.

**Comment by aprokop** [comment]
SYCL failure only due a timeout. Otherwise, good.

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
