### PR TITLE
Switch bvh_driver benchmark to APIv2

### PR DESCRIPTION
**Pull request by aprokop**

### CODE REVIEW

**Comment by aprokop** [comment]
## Construction

`master`
```
-------------------------------------------------------------------------------------------------------------------
Benchmark                                                         Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------------
BM_construction<ArborX::BVH<Serial>>/50000/0/manual_time       4222 us         4224 us          166 rate=11.8417M/s
BM_construction<ArborX::BVH<OpenMP>>/50000/0/manual_time        650 us          663 us          995 rate=76.8979M/s
BM_construction<ArborX::BVH<HIP>>/50000/0/manual_time           251 us          256 us         2726 rate=199.375M/s
BM_construction<BoostRTree>/50000/0/manual_time                7822 us         7876 us           89 rate=6.3924M/s
```

`branch`
```
-------------------------------------------------------------------------------------------------------------------
Benchmark                                                         Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------------
BM_construction<ArborX::BVH<Serial>>/50000/0/manual_time       3598 us         3600 us          194 rate=13.8963M/s
BM_construction<ArborX::BVH<OpenMP>>/50000/0/manual_time        632 us          644 us         1012 rate=79.1417M/s
BM_construction<ArborX::BVH<HIP>>/50000/0/manual_time           234 us          238 us         2785 rate=213.429M/s
BM_construction<BoostRTree>/50000/0/manual_time                7828 us         7886 us           89 rate=6.38745M/s
```

## Search
`master`
```
--------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                  Time             CPU   Iterations UserCounters...
--------------------------------------------------------------------------------------------------------------------------------------------
BM_radius_search<ArborX::BVH<Serial>>/50000/20000/10/1/0/0/0/manual_time               66563 us        66450 us           10 rate=300.468k/s
BM_radius_callback_search<ArborX::BVH<Serial>>/50000/20000/10/1/0/0/0/manual_time      33414 us        33359 us           21 rate=598.557k/s
BM_knn_search<ArborX::BVH<Serial>>/50000/20000/10/1/0/0/manual_time                    66721 us        66622 us           10 rate=299.758k/s
BM_knn_callback_search<ArborX::BVH<Serial>>/50000/20000/10/1/0/0/manual_time           66411 us        66411 us           10 rate=301.157k/s
BM_radius_search<ArborX::BVH<OpenMP>>/50000/20000/10/1/0/0/0/manual_time                1359 us         1363 us          492 rate=14.7207M/s
BM_radius_callback_search<ArborX::BVH<OpenMP>>/50000/20000/10/1/0/0/0/manual_time        690 us          706 us          994 rate=28.9669M/s
BM_knn_search<ArborX::BVH<OpenMP>>/50000/20000/10/1/0/0/manual_time                     1200 us         1205 us          585 rate=16.6602M/s
BM_knn_callback_search<ArborX::BVH<OpenMP>>/50000/20000/10/1/0/0/manual_time            1061 us         1078 us          665 rate=18.8566M/s
BM_radius_search<ArborX::BVH<HIP>>/50000/20000/10/1/0/0/0/manual_time                    852 us          870 us          810 rate=23.4707M/s
BM_radius_callback_search<ArborX::BVH<HIP>>/50000/20000/10/1/0/0/0/manual_time           408 us          432 us         1715 rate=49.0513M/s
BM_knn_search<ArborX::BVH<HIP>>/50000/20000/10/1/0/0/manual_time                         980 us          998 us          711 rate=20.4129M/s
BM_knn_callback_search<ArborX::BVH<HIP>>/50000/20000/10/1/0/0/manual_time                814 us          834 us          851 rate=24.5693M/s
BM_radius_search<BoostRTree>/50000/20000/10/1/0/0/0/manual_time                        36037 us        36038 us           19 rate=554.993k/s
BM_knn_search<BoostRTree>/50000/20000/10/1/0/0/manual_time                             79133 us        79120 us            9 rate=252.739k/s
```

`branch`
```
--------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                  Time             CPU   Iterations UserCounters...
--------------------------------------------------------------------------------------------------------------------------------------------
BM_radius_search<ArborX::BVH<Serial>>/50000/20000/10/1/0/0/0/manual_time               65551 us        65550 us           10 rate=305.107k/s
BM_radius_callback_search<ArborX::BVH<Serial>>/50000/20000/10/1/0/0/0/manual_time      31901 us        31902 us           22 rate=626.943k/s
BM_knn_search<ArborX::BVH<Serial>>/50000/20000/10/1/0/0/manual_time                    55400 us        55401 us           12 rate=361.014k/s
BM_knn_callback_search<ArborX::BVH<Serial>>/50000/20000/10/1/0/0/manual_time           54343 us        54345 us           13 rate=368.031k/s
BM_radius_search<ArborX::BVH<OpenMP>>/50000/20000/10/1/0/0/0/manual_time                1332 us         1337 us          518 rate=15.01M/s
BM_radius_callback_search<ArborX::BVH<OpenMP>>/50000/20000/10/1/0/0/0/manual_time        685 us          705 us         1000 rate=29.2125M/s
BM_knn_search<ArborX::BVH<OpenMP>>/50000/20000/10/1/0/0/manual_time                     1055 us         1060 us          663 rate=18.957M/s
BM_knn_callback_search<ArborX::BVH<OpenMP>>/50000/20000/10/1/0/0/manual_time             901 us          921 us          768 rate=22.2016M/s
BM_radius_search<ArborX::BVH<HIP>>/50000/20000/10/1/0/0/0/manual_time                    819 us          838 us          835 rate=24.4176M/s
BM_radius_callback_search<ArborX::BVH<HIP>>/50000/20000/10/1/0/0/0/manual_time           387 us          412 us         1806 rate=51.6171M/s
BM_knn_search<ArborX::BVH<HIP>>/50000/20000/10/1/0/0/manual_time                         949 us          966 us          728 rate=21.0704M/s
BM_knn_callback_search<ArborX::BVH<HIP>>/50000/20000/10/1/0/0/manual_time                778 us          798 us          887 rate=25.7225M/s
BM_radius_search<BoostRTree>/50000/20000/10/1/0/0/0/manual_time                        36258 us        36247 us           19 rate=551.602k/s
BM_knn_search<BoostRTree>/50000/20000/10/1/0/0/manual_time                             79344 us        79316 us            9 rate=252.066k/s
```

So, everything is a bit faster, as expected.

**Comment by aprokop** [comment]
Just warnings from a container build.

**Comment by Rombur** [comment]
> So, everything is a bit faster, as expected.

Why is it slightly faster?

**Comment by aprokop** [comment]
> Why is it slightly faster?

Storing points instead of boxes, so basic operations like intersections, expansion, and distance calculations are faster.

**Pull request merged**
