### PR TITLE
Indent preprocessor directives

### PR DESCRIPTION
**Pull request by masterleinad**
I find indenting preprocessor directives more readable. What do all y'all think?

### CODE REVIEW

**Comment by aprokop** [comment]
I like it. But I don't understand why it works this way. I tried that before and indented more, even things like:
```c++
#ifndef HEADER
#  define HEADER
```

**Comment by masterleinad** [comment]
Looking at #177, I would appreciate if we can come to some consensus here.

**Comment by aprokop** [comment]
I'm definitely for it if the first #ifndef does not mess up things as you indicate.

**Comment by masterleinad** [comment]
> I'm definitely for it if the first #ifndef does not mess up things as you indicate.

This passes the indentation check.

**Comment by aprokop** [comment]
Actually, some of these are weird, like `clz`. It seems to align `#ifdef` with code, not just based on the macros themselves. Is that expected?

**Comment by masterleinad** [comment]
It seems to match the scope disregarding if the scope is opened by curly braces or a preprocessor directive. We can see the same in `isFinite`. I could argue that it should not do it in functions but prefer it over the alternative of not indenting at all.

**Comment by dalg24** [comment]
I am mildly against that change.  I don't like so much indenting the include directives and IMO it only improves readability in two places, namely
* the Thrust sort workaround for Clang pre 9.0, and 
* the MPI CUDA-aware support checking that did not make it into master yet and that could as well become a configure-time check.

I definitely agree it degrades readability in the kernel level functions as it was pointed out.  Of course, we can disable the format in these places.

My preference would be close that PR until we find more compelling examples or (maybe better) disable the format and indent where you think it matters.

**Comment by sslattery** [comment]
I think this degrades readability - `#` followed by a statement without spaces immediately indicates macro to me

**Comment by masterleinad** [comment]
@dalg24 I made the changes you requested.

**Pull request merged**
