### PR TITLE
Move returnCentroid from KDOP to a general geometry algorithms file

### PR DESCRIPTION
**Pull request by aprokop**
This will allow calling space filling curves on k-DOPs.

### CODE REVIEW

**Comment by aprokop** [comment]
`Clang` and `GCC` passed. Everything else timed out.

**Review by dalg24 — CHANGES_REQUESTED** [review]
Try this instead https://github.com/aprokop/ArborX/pull/15

**Review by dalg24 — CHANGES_REQUESTED** [review]
Try this instead https://github.com/aprokop/ArborX/pull/15

**Review by dalg24 — APPROVED** [review]
Please update the PR description (mention removal of `expand(Box, KDOP)` free function that was superseded by the generic expand that dispatches to blah..)

**Comment by aprokop** [comment]
I have no idea why it fails to compile on Clang. I ask for fresh eyes from someone.

**Comment by aprokop** [comment]
This is a bit too large right now. I moved the part I really care about in #874, and will return to this one at a later day.

**Pull request closed without merging**
