### PR TITLE
Disable skipping CI

### PR DESCRIPTION
**Pull request by masterleinad**

### CODE REVIEW

**Comment by masterleinad** [comment]
OK. I don't know how to fix #229 breaking CI. I tried renaming the regex in different ways and also renaming the original `[skip ci]` commit message but nothing apart from disabling the plugin seems to work.

Let's just revert that pull request for now, so any other pull request can be tested.

**Comment by dalg24** [comment]
I added a "Filter branches by commit message" on the Jenkins side
```
Branches whose last commit's message contains (case insensitive) the pattern "[ci skip]" or "[skip ci]" will be ignored.
```
This is so weird, I would have sworn the build for b354bf3 was skipped but was built when I pushed ee5cc92

Anyway let's move on

**Comment by dalg24** [comment]
Changed to `Filter pull requests by commit message`
branches -> pr

**Comment by masterleinad** [comment]
How do you want to proceed here? If I understand correctly, you changed some `jenkins` settings that make the plugin obsolete. Do you want to test this further here or shall we just merge (possibly removing your two commits)?

**Comment by dalg24** [comment]
> How do you want to proceed here? If I understand correctly, you changed some `jenkins` settings that make the plugin obsolete. Do you want to test this further here or shall we just merge (possibly removing your two commits)?

Merge.  As is if you guys are fine with the changes I piggy-backed (my preference) or drop them.

It's more like another way to trigger the same plugin.  And no I don't want to investigate further.

**Comment by masterleinad** [comment]
If nobody objects, I'll merge later today.

**Pull request merged**
