### PR TITLE
Bugfix bounding volume accesses in generate hierarchy

### LINKED ISSUE #574: Missing memory fencing in the hierarchy construction
Reported by Phillip

Verification of the 10M subset of the 37M HACC problem on Perlmutter (A100) periodically fails:
```
$ ./ArborX_DBSCAN.exe --binary --filename hacc_37M.arborx --core-min-size 2 --eps 0.042 --impl fdbscan --print-dbscan-timers --verify

ArborX version    : 1.2 (dev)
ArborX hash       : 3b02080
eps               : 0.042000
minpts            : 2
cluster min size  : 1
filename          : hacc_37M.arborx [binary, max_pts = -1]
filename [labels] :  [binary]
implementation    : fdbscan
samples           : -1
verify            : true
print timers      : true
output centers    : false
Reading in "hacc_37M.arborx" in binary mode...done
Read in 36902719 3D points
-- construction     :      0.019
-- query+cluster    :      0.453
-- postprocess      :      0.017
total time          :      0.490

#clusters       : 2763469
#cluster points : 23609943 [63.98%]
Core point is marked as noise: 33854419 [-1]
Core point is marked as noise: 33855004 [-1]
Core point is marked as noise: 33855599 [-1]
Core point is marked as noise: 33855517 [-1]
Core point is marked as noise: 33855727 [-1]
Verification failed
```
The failures may be different between the runs: sometimes they are "core point marked as noise", sometimes "noise points does not have index -1". All this points to a generally corrupted `labels` array.

The interesting thing is that neither GTX1070 (Pascal), nor V100 (Volta) have any failures, even when trying multiple times.

So far, there’s only one thing that comes to mind that may somewhat explain this failure. We use union-find algorithm for merging from [this](https://doi.acm.org/10.1145/3208040.3208041) paper. It uses lock-free mechanism to update the labels. Specifically, in the last paragraph on page 4 of the paper it talks about updating a single aligned machine word stating it is therefore atomic. If this somehow does not hold on A100, then all hell could break lose. I’ll need to see if I can introduce some extra locking atomics into the union-find algorithm to test this idea.

### PR DESCRIPTION
**Pull request by dalg24**
Fix #574 

~~Only a draft because current solution does not play well with #575~~
nevermind it does not use `HappyTreeFriends::getBoundingVolume`

### CODE REVIEW

**Comment by aprokop** [comment]
The first commit (c7e02f9) does not fix the problem (but runs fast, similar to master). The second commit (44cdf33) fixes the problem. Seems to run fast, but needs testing across architectures.

**Comment by aprokop** [comment]
@dalg24 Can you comment on whether using `store_fence` or `load_fence` is appropriate here instead of full `memory_fence`? I think it's not, but wanted check.

**Comment by aprokop** [comment]
So, the first item that I propose is simply disabling memory fences for the Serial space (and, in fact, that would also solve the compilation issue when Kokkos Serial atomics are not enabled).

That still leaves an open question about OpenMP on Spock. Looking at [Kokkos_MemoryFence.hpp](https://github.com/kokkos/kokkos/blob/2879e23507bcb21adb739d6317b3430f665de4a6/core/src/impl/Kokkos_Memory_Fence.hpp), I don't see any special checks for the AMD hardware. Is there anything missing there? If not, is there a known issue with slow fences on AMD host?

**Comment by dalg24** [comment]
The memory fence can be replaced by a `Kokkos::store_fence()` or alternatively we can place a `Kokkos::load_fence` before the `expand()` call in the left and right children branches.

We could also look into using Desul atomics.

**Comment by aprokop** [comment]
I quickly tried the following patch:
```diff
--- a/src/details/ArborX_DetailsTreeConstruction.hpp
+++ b/src/details/ArborX_DetailsTreeConstruction.hpp
@@ -308,6 +308,12 @@ public:
         // parent, and thus requires knowing the ranges of both children.
         int const apetrei_parent = range_right;

+        // Do memory flushing if we are likely to be the first thread up. This
+        // is necessary for bounding box of the current node, as it will be
+        // accessed by the other thread.
+        if (_ranges(apetrei_parent) == UNTOUCHED_NODE)
+            Kokkos::memory_fence();
+
         // The range of the parent is the union of the ranges of children. Each
         // child updates one of these range values, the farthest from the
         // split. The first thread up stores the updated range value (which
@@ -343,6 +349,9 @@ public:

         int const apetrei_parent = range_left - 1;

+        if (_ranges(apetrei_parent) == UNTOUCHED_NODE)
+            Kokkos::memory_fence();
+
         range_left = Kokkos::atomic_compare_exchange(
             &_ranges(apetrei_parent), UNTOUCHED_NODE, range_right);
         if (range_left == UNTOUCHED_NODE)
```
And it also seems to work correctly. I'm not sure it is correct, though.

> The memory fence can be replaced by a Kokkos::store_fence() or alternatively we can place a Kokkos::load_fence before the expand() call in the left and right children branches.

What's the benefit of doing that? Looking at the code, the only difference is that it has a special path for `#if defined(KOKKOS_ENABLE_ASM) && defined(KOKKOS_ENABLE_ISA_X86_64)`, but I'm not sure if that is helpful.

**Comment by aprokop** [comment]
So I printed Kokkos configuration on Spock, and it has `KOKKOS_ENABLE_ISA_X86_64: no`. Thus, `store_fence` and `load_fence` are identical to `memory_fence` there. 

It also has `KOKKOS_ENABLE_GNU_ATOMICS: yes`, so `memory_fence()` is doing `__sync_synchronize()`.

**Comment by dalg24** [comment]
Try to replace the memory fence with `desul::atomic_thread_fence(desul::MemoryOrderRelease(), desul::MemoryScopeCore())`

**Comment by aprokop** [comment]
I tried the following patches on Spock.

## Patch 1
```diff
--- a/src/details/ArborX_DetailsTreeConstruction.hpp
+++ b/src/details/ArborX_DetailsTreeConstruction.hpp
@@ -308,6 +308,14 @@ public:
         // parent, and thus requires knowing the ranges of both children.
         int const apetrei_parent = range_right;

+        // Do memory flushing if we are likely to be the first thread up. This
+        // is necessary for bounding box of the current thread's node to be
+        // available to other threads. Do not do the fence if we can guarantee
+        // this is the second thread up, as it no other thread will read this
+        // storage.
+        if (_ranges(apetrei_parent) == UNTOUCHED_NODE)
+            Kokkos::store_fence();
+
         // The range of the parent is the union of the ranges of children. Each
         // child updates one of these range values, the farthest from the
         // split. The first thread up stores the updated range value (which
@@ -334,7 +342,11 @@ public:

         delta_right = delta(range_right);

-        expand(bounding_volume, getNodePtr(right_child)->bounding_volume);
+        // Make sure that the bounding box of the other thread is correctly loaded.
+        auto const& right_child_bounding_volume =
+                getNodePtr(right_child)->bounding_volume;
+        Kokkos::load_fence();
+        expand(bounding_volume, right_child_bounding_volume);
       }
       else
       {
@@ -343,6 +355,9 @@ public:

         int const apetrei_parent = range_left - 1;

+        if (_ranges(apetrei_parent) == UNTOUCHED_NODE)
+            Kokkos::store_fence();
+
         range_left = Kokkos::atomic_compare_exchange(
             &_ranges(apetrei_parent), UNTOUCHED_NODE, range_right);
         if (range_left == UNTOUCHED_NODE)
@@ -355,7 +370,11 @@ public:

         delta_left = delta(range_left - 1);

-        expand(bounding_volume, getNodePtr(left_child)->bounding_volume);
+        // Make sure that the bounding box of the other thread is correctly loaded.
+        auto const& left_child_bounding_volume =
+                getNodePtr(left_child)->bounding_volume;
+        Kokkos::load_fence();
+        expand(bounding_volume, left_child_bounding_volume);
       }

       // Having the full range for the parent, we can compute the Karras index.
```
This is essentially a `memory_fence()` patch, except tries to be a bit smart about how it does that. 

## Patch 2
Suggested by @dalg24 
```diff
--- a/src/details/ArborX_DetailsTreeConstruction.hpp
+++ b/src/details/ArborX_DetailsTreeConstruction.hpp
@@ -367,7 +367,7 @@ public:
       setRightChild(parent_node, right_child);
       setRope(parent_node, range_right, delta_right);
       parent_node->bounding_volume = bounding_volume;
-      Kokkos::memory_fence();
+      desul::atomic_thread_fence(desul::MemoryOrderRelease(), desul::MemoryScopeDevice());

       i = karras_parent;
```

Both patches are significantly better than a single `memory_fence()` call. The second patch is slightly faster than the first on Spock:
```
BM_construction<ArborX::BVH<Serial>>/1000/0/manual_time_median                   +0.0175         +0.0171            93            94            98           100
BM_construction<ArborX::BVH<OpenMP>>/1000/0/manual_time_median                   +0.0530         +0.0490            93            98            99           103
BM_construction<ArborX::BVH<HIP>>/1000/0/manual_time_median                      -0.0075         -0.0071           679           674           683           678
BM_construction<ArborX::BVH<Serial>>/1000/1/manual_time_median                   -0.0014         -0.0007            95            95           100           100
BM_construction<ArborX::BVH<OpenMP>>/1000/1/manual_time_median                   -0.0219         -0.0238            98            96           105           102
BM_construction<ArborX::BVH<HIP>>/1000/1/manual_time_median                      -0.0130         -0.0137           685           676           688           679
BM_construction<ArborX::BVH<Serial>>/10000/0/manual_time_median                  -0.0191         -0.0195           473           464           480           470
BM_construction<ArborX::BVH<OpenMP>>/10000/0/manual_time_median                  -0.0358         -0.0369           192           185           198           191
BM_construction<ArborX::BVH<HIP>>/10000/0/manual_time_median                     -0.0084         -0.0080           736           730           739           734
BM_construction<ArborX::BVH<Serial>>/10000/1/manual_time_median                  -0.0184         -0.0190           477           469           484           474
BM_construction<ArborX::BVH<OpenMP>>/10000/1/manual_time_median                  -0.0258         -0.0251           202           197           209           203
BM_construction<ArborX::BVH<HIP>>/10000/1/manual_time_median                     -0.0439         -0.0422           771           737           773           740
BM_construction<ArborX::BVH<Serial>>/100000/0/manual_time_median                 -0.0039         -0.0038          4220          4204          4226          4209
BM_construction<ArborX::BVH<OpenMP>>/100000/0/manual_time_median                 -0.0011         -0.0009           872           871           878           877
BM_construction<ArborX::BVH<HIP>>/100000/0/manual_time_median                    -0.0016         +0.0006          1025          1024          1049          1049
BM_construction<ArborX::BVH<Serial>>/100000/1/manual_time_median                 -0.0166         -0.0166          4389          4316          4395          4322
BM_construction<ArborX::BVH<OpenMP>>/100000/1/manual_time_median                 +0.0043         +0.0045          1069          1074          1075          1080
BM_construction<ArborX::BVH<HIP>>/100000/1/manual_time_median                    -0.0158         -0.0149          1059          1042          1084          1068
BM_construction<ArborX::BVH<Serial>>/1000000/0/manual_time_median                -0.0041         -0.0041         81306         80976         81517         81184
BM_construction<ArborX::BVH<OpenMP>>/1000000/0/manual_time_median                -0.0180         -0.0181          9030          8868          9347          9178
BM_construction<ArborX::BVH<HIP>>/1000000/0/manual_time_median                   -0.0613         -0.0617          2526          2371          2540          2383
BM_construction<ArborX::BVH<Serial>>/1000000/1/manual_time_median                -0.0345         -0.0345         87383         84370         87593         84575
BM_construction<ArborX::BVH<OpenMP>>/1000000/1/manual_time_median                +0.0107         +0.0100         10973         11090         11254         11366
BM_construction<ArborX::BVH<HIP>>/1000000/1/manual_time_median                   -0.0632         -0.0640          2535          2375          2550          2386
```

Comparing the second patch (desul) with master on Spock shows a minor slowdown for larger sizes on HIP
```diff
 compare_bench.py benchmarks 202112100004_master_0fd9c4a.json 202112100004_memoryfence_d5a69c0.json| grep median
BM_construction<ArborX::BVH<Serial>>/1000/0/manual_time_median                   -0.0220         -0.0204            96            94           102           100
BM_construction<ArborX::BVH<OpenMP>>/1000/0/manual_time_median                   +0.0304         +0.0302            95            98           100           103
BM_construction<ArborX::BVH<HIP>>/1000/0/manual_time_median                      +0.0160         +0.0165           664           674           667           678
BM_construction<ArborX::BVH<Serial>>/1000/1/manual_time_median                   -0.0168         -0.0132            96            95           102           100
BM_construction<ArborX::BVH<OpenMP>>/1000/1/manual_time_median                   -0.0046         -0.0025            97            96           102           102
BM_construction<ArborX::BVH<HIP>>/1000/1/manual_time_median                      +0.0062         +0.0052           672           676           676           679
BM_construction<ArborX::BVH<Serial>>/10000/0/manual_time_median                  +0.0062         +0.0071           462           464           467           470
BM_construction<ArborX::BVH<OpenMP>>/10000/0/manual_time_median                  +0.0190         +0.0200           182           185           187           191
BM_construction<ArborX::BVH<HIP>>/10000/0/manual_time_median                     +0.0100         +0.0098           723           730           726           734
BM_construction<ArborX::BVH<Serial>>/10000/1/manual_time_median                  -0.0194         -0.0192           478           469           484           474
BM_construction<ArborX::BVH<OpenMP>>/10000/1/manual_time_median                  -0.0105         -0.0090           199           197           205           203
BM_construction<ArborX::BVH<HIP>>/10000/1/manual_time_median                     +0.0106         +0.0105           729           737           733           740
BM_construction<ArborX::BVH<Serial>>/100000/0/manual_time_median                 +0.0071         +0.0071          4174          4204          4179          4209
BM_construction<ArborX::BVH<OpenMP>>/100000/0/manual_time_median                 -0.0088         -0.0084           879           871           884           877
BM_construction<ArborX::BVH<HIP>>/100000/0/manual_time_median                    +0.0038         +0.0036          1020          1024          1046          1049
BM_construction<ArborX::BVH<Serial>>/100000/1/manual_time_median                 +0.0105         +0.0106          4272          4316          4277          4322
BM_construction<ArborX::BVH<OpenMP>>/100000/1/manual_time_median                 +0.0071         +0.0076          1066          1074          1072          1080
BM_construction<ArborX::BVH<HIP>>/100000/1/manual_time_median                    +0.0071         +0.0077          1035          1042          1060          1068
BM_construction<ArborX::BVH<Serial>>/1000000/0/manual_time_median                -0.0094         -0.0097         81748         80976         81982         81184
BM_construction<ArborX::BVH<OpenMP>>/1000000/0/manual_time_median                -0.0196         -0.0200          9046          8868          9365          9178
-BM_construction<ArborX::BVH<HIP>>/1000000/0/manual_time_median                   +0.0890         +0.0887          2177          2371          2189          2383
BM_construction<ArborX::BVH<Serial>>/1000000/1/manual_time_median                -0.0118         -0.0119         85381         84370         85590         84575
BM_construction<ArborX::BVH<OpenMP>>/1000000/1/manual_time_median                +0.0059         +0.0054         11026         11090         11305         11366
BM_construction<ArborX::BVH<HIP>>/1000000/1/manual_time_median                   +0.0282         +0.0291          2310          2375          2319          2386
```
But the DBSCAN problem construction (37M points) on HIP does not show any difference between master and desul, both completing in 0.38s.

**Comment by aprokop** [comment]
Examination of 5 variants

## Variant 1
```diff
--- a/src/details/ArborX_DetailsTreeConstruction.hpp
+++ b/src/details/ArborX_DetailsTreeConstruction.hpp
@@ -334,6 +334,8 @@ public:

         delta_right = delta(range_right);

+        // Make sure that the bounding box of the other thread is correctly loaded.
+        Kokkos::load_fence();
         expand(bounding_volume, getNodePtr(right_child)->bounding_volume);
       }
       else
@@ -355,6 +357,7 @@ public:

         delta_left = delta(range_left - 1);

+        Kokkos::load_fence();
         expand(bounding_volume, getNodePtr(left_child)->bounding_volume);
       }
```

## Variant 2
```diff
--- a/src/details/ArborX_DetailsTreeConstruction.hpp
+++ b/src/details/ArborX_DetailsTreeConstruction.hpp
@@ -367,6 +367,7 @@ public:
       setRightChild(parent_node, right_child);
       setRope(parent_node, range_right, delta_right);
       parent_node->bounding_volume = bounding_volume;
+      desul::atomic_thread_fence(desul::MemoryOrderRelease(), desul::MemoryScopeDevice());

       i = karras_parent;
```

## Variant 3
```diff
--- a/src/details/ArborX_DetailsTreeConstruction.hpp
+++ b/src/details/ArborX_DetailsTreeConstruction.hpp
@@ -334,6 +334,7 @@ public:

         delta_right = delta(range_right);

+        desul::atomic_thread_fence(desul::MemoryOrderAcquire(), desul::MemoryScopeDevice());
         expand(bounding_volume, getNodePtr(right_child)->bounding_volume);
       }
       else
@@ -355,6 +356,7 @@ public:

         delta_left = delta(range_left - 1);

+        desul::atomic_thread_fence(desul::MemoryOrderAcquire(), desul::MemoryScopeDevice());
         expand(bounding_volume, getNodePtr(left_child)->bounding_volume);
       }
```

## Variant 4
```diff
--- a/src/details/ArborX_DetailsTreeConstruction.hpp
+++ b/src/details/ArborX_DetailsTreeConstruction.hpp
@@ -366,7 +366,7 @@ public:
       parent_node->left_child = left_child;
       setRightChild(parent_node, right_child);
       setRope(parent_node, range_right, delta_right);
-      parent_node->bounding_volume = bounding_volume;
+      desul::atomic_store(&parent_node->bounding_volume, bounding_volume, desul::MemoryOrderRelease(), desul::MemoryScopeDevice());

       i = karras_parent;
```

## Variant 5
```diff
--- a/src/details/ArborX_DetailsTreeConstruction.hpp
+++ b/src/details/ArborX_DetailsTreeConstruction.hpp
@@ -334,7 +334,7 @@ public:

         delta_right = delta(range_right);

-        expand(bounding_volume, getNodePtr(right_child)->bounding_volume);
+        expand(bounding_volume, desul::atomic_load(&getNodePtr(right_child)->bounding_volume, desul::MemoryOrderAcquire(), desul::MemoryScopeDevice()));
       }
       else
       {
@@ -355,7 +355,7 @@ public:

         delta_left = delta(range_left - 1);

-        expand(bounding_volume, getNodePtr(left_child)->bounding_volume);
+        expand(bounding_volume, desul::atomic_load(&getNodePtr(left_child)->bounding_volume, desul::MemoryOrderAcquire(), desul::MemoryScopeDevice()));
       }

       // Having the full range for the parent, we can compute the Karras index.
```

**Comment by aprokop** [comment]
Given the results in the previous comment, I propose going with variant1 without using desul. As a side effect, this would eliminate the requirement to update to Kokkos 3.5.

**Review by aprokop — APPROVED** [review]

**Comment by dalg24** [comment]
@Rombur @masterleinad please review as both Andrey and I are author on this one.

**Review by masterleinad — APPROVED** [review]
Looks OK to me.

**Comment by aprokop** [comment]
@dalg24 I keep thinking about this after the merge, and I'm still not sure if only the `load_fence()` is the right thing there. Should it not be the full `memory_fence()` instead?

**Comment by dalg24** [comment]
> @dalg24 I keep thinking about this after the merge, and I'm still not sure if only the `load_fence()` is the right thing there. Should it not be the full `memory_fence()` instead?

This is the right thing.

**Pull request merged**
