### PR TITLE
Run Style check before Builds

### LINKED ISSUE #378: Run Style checks even if one of the builds fails
[Pipeline: Basic Steps](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/) plugin provides [`catchError`](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#catcherror-catch-error-and-set-build-result-to-failure). This way, other stages can be run if one of the stages failed even in non-parallel stages.

We could put Style in the beginning of the pipeline and change it to:
```
stage("Style") {                                                                                                                                              
    agent {                                                                                                                                                   
        docker {                                                                                                                                              
            // arbitrary image that has clang-format version 7.0                                                                                              
            image "dalg24/arborx_base:19.04.0-cuda-9.2"                                                                                                       
            label 'docker'                                                                                                                                    
        }                                                                                                                                                     
    }                                                                                                                                                         
    steps {                                                                                                                                                   
        catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {                                                                                          
            sh './scripts/check_format_cpp.sh'                                                                                                                
        }                                                                                                                                                     
    }                                                                                                                                                         
} 
```

### PR DESCRIPTION
**Pull request by aprokop**
Testing fix #378

### CODE REVIEW

**Comment by aprokop** [comment]
This seems to run as expected. However, I cannot do a final check (that the whole testing fails if Style fails but builds run) due to HIP failure.

**Review by dalg24 — APPROVED** [review]

**Comment by masterleinad** [comment]
You can always just disable HIP for one commit to check if it works as expected.

**Comment by aprokop** [comment]
> You can always just disable HIP for one commit to check if it works as expected.

Very good point, did not occur to me.

**Comment by aprokop** [comment]
OK, it does not do what I expected. Failing Style check does not result in overall failure.

**Review by dalg24 — CHANGES_REQUESTED** [review]
>  Failing Style check does not result in overall failure.

That's bad because we would overlook non-compliance

**Comment by aprokop** [comment]
The one time HIP passes, and Clang build runs out of space on cathode.

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
