### PR TITLE
Update version to 1.6 dev

### PR DESCRIPTION
**Pull request by aprokop**
Still struggle to figure out whether it should be 1.6 or 2.0.

### CODE REVIEW

**Comment by aprokop** [comment]
One thing is that we still have `SameMajorVersion` compatibility, and not `AnyNewerVersion`. Not sure whether we want to switch.

**Comment by Rombur** [comment]
> Still struggle to figure out whether it should be 1.6 or 2.0.

We found out in deal.II that it's a lot easier to decide before the release to go from `1.6` to `2.0` than the other way around because downstream app may decide to differentiate their code on the major version as soon as we update the version to `2.0`

> One thing is that we still have SameMajorVersion compatibility, and not AnyNewerVersion. Not sure whether we want to switch.

We should use `AnyNewerVersion` and let the user decide what to do. `SameMajorVersion` is too restrictive.

**Comment by masterleinad** [comment]
> We should use `AnyNewerVersion` and let the user decide what to do. `SameMajorVersion` is too restrictive.

I agree.

**Review by masterleinad — APPROVED** [review]

**Comment by aprokop** [comment]
Unrelated failures in distributed test (sporadic).

**Pull request merged**
