### PR TITLE
Bump Kokkos to 3.6 in gitlab

### PR DESCRIPTION
**Pull request by aprokop**

### CODE REVIEW

**Comment by aprokop** [comment]
@masterleinad Do you need to manually rebuild Kokkos for it to be picked up? Seems like it's not being built automatically.

**Comment by masterleinad** [comment]
Yes, you need to let it build `Kokkos` once by replacing 
````
.BuildKokkos:
```
with
```
BuildKokkos:
```
I would also be fine with doing this every time we trigger the `GitLab` pipeline. In the end, building `Kokkos` is much cheaper than running the benchmark.

**Comment by aprokop** [comment]
Building Kokkos took ~2 min. The overall time took ~41 min. At the same time, we could comment it back now that it's been built.

**Comment by aprokop** [comment]
Disabled building Kokkos by default. Should be fine.

**Pull request merged**
