### PR TITLE
Disable ArborX_TreeViz if Kokkos is built without Serial

### PR DESCRIPTION
**Pull request by masterleinad**
Kokkos is allowed to be built without `Serial` but this example requires it.

### CODE REVIEW

**Comment by dalg24** [comment]
> In `tests/CMakeLists.txt` we use
> 
> ```
> if(Kokkos_DEVICES MATCHES "Serial")                                                                                                                                         
> ```
> 
> Note the case. Which one is correct? Or is it case-insensitive?

It is case sensitive.  After kokkos cmake overhaul it will be uppercase.  Good catch.

**Comment by masterleinad** [comment]
> It is case sensitive. After kokkos cmake overhaul it will be uppercase. Good catch.

Yeah, I am also working on top off a recent `kokkos` version.

**Comment by dalg24** [comment]
Squash your commits

**Comment by aprokop** [comment]
@dalg24 Just did squash and merge.

**Comment by masterleinad** [comment]
@aprokop Thanks!

**Pull request merged**
