### PR TITLE
Add and install ArborXConfigVersion.cmake

### PR DESCRIPTION
**Pull request by Rombur**
We don't export the version in a way that's useful for CMake, i.e., `find_package(ArborX 1.0)` does not work. This PR fixes that. We need to decide what kind of compatibility we want. Currently if you require 1.1, 1.2 will work but 2.0 won't.

### CODE REVIEW

**Comment by aprokop** [comment]
[CMake documentation reference](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html)

I'm fine with either `SameMajorVersion` or `AnyNewerVersion`. Would prefer `SameMajorVersion`, as it would allow to break backwards compatibility with new major versions.

**Review by aprokop — COMMENTED** [review]
Should we update the `CMakeLists.txt` in the `examples/` for installation to test that it works post-installation?

**Comment by Rombur** [comment]
What do you mean? The examples do not use `find_package` right?

**Comment by masterleinad** [comment]
We also test the examples with an installed `ArborX` package, see
https://github.com/arborx/ArborX/blob/785a78ce17c4960b2adf00f5e0c150ab4bd4455e/examples/CMakeLists.txt#L2-L5
and could require a version there.

**Review by masterleinad — APPROVED** [review]

**Comment by aprokop** [comment]
I feel like we should have a separate `ARBORX_VERSION` in addition to `ARBORX_VERSION_STRING`. `ARBORX_VERSION` would be machine-readable thing like 1.1, while `ARBORX_VERSION_STRING` could be `1.1 (dev)`. Then, in the examples, we could use `ARBORX_VERSION` without hardcoding 1.1.

**Comment by Rombur** [comment]
I thought the point of adding the version in the examples was to show users how it works. Otherwise, I don't see what's the point of requiring a version in the examples.

**Comment by aprokop** [comment]
> I thought the point of adding the version in the examples was to show users how it works.

That's fair. The only caveat is that we may need to remember to update it there at some point.

**Comment by Rombur** [comment]
Right I was going to add a step in `ReleaseSteps.md`

**Review by aprokop — APPROVED** [review]

**Pull request merged**
