### PR TITLE
Add Pthread backend and check for empty list of backends

### PR DESCRIPTION
**Pull request by masterleinad**
Not checking for the device types we support gave me some pretty hard to understand errors.

### CODE REVIEW

**Comment by masterleinad** [comment]
I wanted to try another parallel backend that might be simpler to debug than `OpenMP` and it seems to work out of the box. Any reason not to support it?

**Comment by aprokop** [comment]
> Any reason not to support it?

No strong reason. `Pthread` is uncommon, though, and is rarely enabled, I believe.

**Comment by dalg24** [comment]
If you want to support, enable on one CI build at least.

**Comment by masterleinad** [comment]
There was some error with fetching the gpg-key (for `CMake` I believe) and I fixed a typo I introduced at some point in the `.jenkins` file for the `CMake` options.

**Comment by masterleinad** [comment]
Let's just go with the simplified version in #190.

**Pull request closed without merging**
