### PR TITLE
Switch one CI build to test Kokkos 3.5.00

### PR DESCRIPTION
**Pull request by aprokop**

### CODE REVIEW

**Comment by aprokop** [comment]
It seems that it's not possible to deduce which version of Kokkos is being built when looking at Jenkins.

**Comment by dalg24** [comment]
> It seems that it's not possible to deduce which version of Kokkos is being built when looking at Jenkins.

They are several ways we could go about it.  We could suggest on the Kokkos side to add in the exported configuration so it gets printed when not found in quiet mode.  On our side we could print the info after `find_package(Kokkos)`

**Comment by aprokop** [comment]
> They are several ways we could go about it. We could suggest on the Kokkos side to add in the exported configuration so it gets printed when not found in quiet mode. On our side we could print the info after `find_package(Kokkos)`

I think both are reasonable. Kokkos should do that. But in the shorter time frame, we could also add that to ArborX.

**Comment by dalg24** [comment]
You still need to provide a rational for the changes you are proposing.

**Comment by aprokop** [comment]
In the spherical overdensity and hdbscan PRs I use `Kokkos:atomic_min` not available in Kokkos 3.4. This allows for a simpler code as I don't have to provide volatile overloads. I would like to be able to test these. 3.4.01 is optional.

**Comment by dalg24** [comment]
I am not following how that is helping.  Are you conditionally enabling if Kokkos version is sufficient?

**Comment by aprokop** [comment]
> Are you conditionally enabling if Kokkos version is sufficient?

I'm not at the moment, but I should. That's an oversight.

**Comment by dalg24** [comment]
> And in general, I think it is a good idea to test Kokkos versions we support.

Sure.  No one is going to argue with you on this

> I see no downside to this, as this extends our coverage.

We are not extending anything if we change the version instead of adding a new build.
I am not necessarily to change the versions in a few builds but I am curious why you selected these.

**Comment by aprokop** [comment]
> I am not necessarily to change the versions in a few builds but I am curious why you selected these.

Just all Kokkos releases starting from the one we require and including the latest.

**Review by masterleinad — APPROVED** [review]

**Pull request merged**
