### PR TITLE
Remove hardcoded float from DistributedTree nearest query

### PR DESCRIPTION
**Pull request by aprokop**
It wasn't possible to run nearest queries with `double`:
```
<snip>/src/distributed/detail/ArborX_DistributedTreeNearestHelpers.hpp:94:12:
error: no viable constructor or deduction guide for deduction of template arguments of 'Sphere'
   94 |     return Sphere{Details::convert<::ArborX::Point<DIM, Coordinate>>(point), r};
      |            ^
<snip>/arborx/src/distributed/detail/ArborX_DistributedTreeNearestHelpers.hpp:144:60:
note: in instantiation of function template specialization
 'ArborX::Details::Dispatch::approx_expand_by_radius<
ArborX::GeometryTraits::PointTag, ArborX::Point<3, double>>::apply<float>' requested here
  144 |       typename GeometryTraits::tag_t<Geometry>, Geometry>::apply(geometry, r);
```
I realized we had a few instances of hardcoded `float` in the nearest queries. This PR fixes this. 

We still don't have done refactoring of testing to test multiple precisions. This would need to be addressed.

### CODE REVIEW

**Comment by aprokop** [comment]
Note that we have other hardcoded floats around. Particularly problematic are the ones in `TreeTraversal`, but there are also a bunch in clustering. These will be addressed in follow-up PRs.

**Review by dalg24 — COMMENTED** [review]
Please add a test that would trigger that issue that is being resolved

**Comment by aprokop** [comment]
> Please add a test that would trigger that issue that is being resolved

I thought about it. Right now, the only way to add that test is to duplicate one of the existing, as we don't have proper framework to test multiple floating types. That ok?

**Review by dalg24 — APPROVED** [review]
Sure

**Pull request merged**
