### PR TITLE
Use ropes for all backends

### PR DESCRIPTION
**Pull request by masterleinad**
I see up to 10% faster results for our performance benchmark and around 17% for DBScan.

### CODE REVIEW

**Comment by masterleinad** [comment]
https://code.ornl.gov/ecpcitest/alexa/-/jobs/1145311

**Comment by masterleinad** [comment]
Looks like `Serial` (and `OpenMP` if it can be trusted) are 10% faster on the performance regression tester for `radius_[callback_]search`.

**Comment by aprokop** [comment]
Results from Crusher and Summit. Other than a single OpenMP case on Crusher (`BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/0/0/1/3`), which is 40% slower, everything else seems to not make much of a difference.

[sycl_ropes.zip](https://github.com/arborx/ArborX/files/8911531/sycl_ropes.zip)

I think it should be fine to remove the non-rope code.

**Comment by masterleinad** [comment]
> I think it should be fine to remove the non-rope code.

So we can merge this?

**Comment by aprokop** [comment]
> So we can merge this?

If we do remove the ropes, I think it should be done fully. That means removing the corresponding node type, and the corresponding traversal. Would also simplify certain places in the construction and traversal where we do SFINAE depending on the node type.

I'm not sure if everyone agrees on that, and whether there is a sentiment to keep a node with two children just in case we need it in the future.

**Comment by masterleinad** [comment]
I thought we were saying to do this first and do the other clean-up later if using ropes is not slower. 
I think it's sensible to keep the Node infrastructure we have in case we want to play with something else at the very least.
I don't think that it's necessary to remove `NodeWithTwoChildren` completely but I would also be fine with that.

**Review by dalg24 — APPROVED** [review]
I am fine with the change proposed.  I can do the code cleanup next week.

PS make sure you update the PR title line

**Comment by masterleinad** [comment]
> I am fine with the change proposed. I can do the code cleanup next week.

I really don't care much either way if you do it or I but I guess you have specific plans in mind.

> I am fine with the change proposed. I can do the code cleanup next week.

Done.

**Comment by masterleinad** [comment]
Retest this please.

**Review by aprokop — APPROVED** [review]

**Pull request merged**
