### PR TITLE
Fix copy operators through a MPI wrapper

### LINKED ISSUE #368: Double free when making copies of a distributed tree
This occurred to me when reviewing ECP-copa/Cabana#295
The implicitly-declared copy constructor and copy assignment operator are problematic because they make copies of the communicator data member and when an object gets out of scope `MPI_Comm_free` gets called on it.
https://github.com/arborx/ArborX/blob/4834bff44c23c9510c6ed93366638dcdf85ab217/src/ArborX_DistributedSearchTree.hpp#L45

### PR DESCRIPTION
**Pull request by masterleinad**
Alternative to #369. Fixes #368.

### CODE REVIEW

**Comment by aprokop** [comment]
One thing that I have not considered in suggesting this approach is the cost `MPI_Comm_dup`. I could not find any concrete information on it, but from my memory it's non-trivial. If it is indeed the case, this approach may incur some penalty for every copy.

**Comment by masterleinad** [comment]
Of course. I wouldn't consider copies to be cheap and don't expect users to copy these objects frequently. In particular, I expect `DistributedSeachTree::query` to be much more expensive.

**Comment by aprokop** [comment]
I have trouble finding the concrete details, but I think `MPI_Comm_dup` is a collective call. So, this patch will newly require that if one process copies the distributed tree, all of them do. This is in addition to acting as a barrier.

**Review by dalg24 — COMMENTED** [review]
Your solution is elegant but I fear that by trying to solve an issue https://github.com/arborx/ArborX/issues/368#issuecomment-691188357 that I am not convinced we need to address in the first place, we might open the door to some subtle bugs.

**Comment by aprokop** [comment]
For me, the edge goes to merging #369 over this one. Not because it is necessarily better, but because I fully understand how it works and what restrictions it has. With this PR, I don't feel like I understand the situation fully, or identify all the possible interactions.

**Comment by masterleinad** [comment]
Let's just go with #369.

**Pull request closed without merging**
