### PR TITLE
Consolidate all geometry unit test into a single executable

### PR DESCRIPTION
**Pull request by dalg24**
My intent is to add the kDOP unit test to this same executable.

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Fine with me.

**Review by aprokop — APPROVED** [review]
LGTM

**Comment by dalg24** [comment]
Warnings are coming from build oneAPI from the `compile.py` script that has no easy way of suppressing warnings.  Just merging as is.

**Comment by aprokop** [comment]
> Warnings are coming from build oneAPI from the `compile.py` script that has no easy way of suppressing warnings. Just merging as is.

Would you be against building with `2>/dev/null`? Maybe we could simply do that, and then check `$?`.

**Comment by dalg24** [comment]
We rebuild only occasionally and I don't remember seeing that before.  Let's not deal with it unless we absolutely have to.

**Pull request merged**
