### PR TITLE
use different master branch on GitLab CI

### PR DESCRIPTION
**Pull request by masterleinad**
This should fix that GitLab CI, see https://code.ornl.gov/ecpcitest/alexa/-/pipelines/181950.

### CODE REVIEW

**Comment by aprokop** [comment]
@masterleinad Can you please provide some description as to what the problem was, and how this fixes it? I have trouble figuring it.

**Comment by masterleinad** [comment]
For some reason, we don't synchronize `GitLab` `master` with `GitHub` `master` but `GitLab` `arborx/ArborX/master` is up-to-date with `GitHub` `master`.
Also, I forgot to enable building a new `Kokkos` version once. Thus, the second commit triggers building an updated `Kokkos` version and the third one reverts the change so that we don't rebuild `Kokkos` with every commit.

**Comment by aprokop** [comment]
> For some reason, we don't synchronize `GitLab` `master` with `GitHub` `master` but `GitLab` `arborx/ArborX/master` is up-to-date with `GitHub` `master`.

Interesting. What is the hash of GitLab's `master`? Is it the one pre-force push, or some even older one?

**Comment by masterleinad** [comment]
> Interesting. What is the hash of GitLab's `master`? Is it the one pre-force push, or some even older one?

It's "Merge pull request #593 from dalg24/do_not_use_kokkos_impl_min_max_functor"(fcf0ceb7).

**Review by aprokop — APPROVED** [review]

**Pull request merged**
