### PR TITLE
Stop pretending we can cherry-pick Kokkos headers

### PR DESCRIPTION
**Pull request by dalg24**
The only headers other than `<Kokkos_Core.hpp>` that may be included specifically are `Kokkos_Macros.hpp` or things like `Kokkos_Pair.hpp` or `Kokkos_Array.hpp`

### CODE REVIEW

**Comment by masterleinad** [comment]
What is the rationale for this change? Did anything stop working?

>  I'm not sure if we have a single file included everywhere. If we do, we could move it there and get rid of everywhere else.

We only have `ArborX_Config.hpp` for files that use configuration macro variables.

**Comment by dalg24** [comment]
> Did anything stop working?

Yes my iMac doesn't let me connect anymore

> What is the rationale for this change? 

Did you ever try to compile something like
```C++
#include <Kokkos_View.hpp>
void foo(Kokkos::View<int>) {}
```

This is just straight up wrong, if you want to use `Kokkos::View` you have to include `<Kokkos_Core.hpp>`.

**Comment by dalg24** [comment]
This used to not compile either
```C++
#include <Kokkos_Array.hpp>
int main(int argc, char *argv[])
{
  Kokkos::Array<int, 3> a;
  return 0;
}
```
Bruno and I fixed it on at least two separate occasion.

`Kokkos::View` is a lost cause.

**Comment by masterleinad** [comment]
> Did you ever try to compile something like
> 
> ```c++
> #include <Kokkos_View.hpp>
> void foo(Kokkos::View<int>) {}
> ```

No, I have not. Didn't expect that to not work.

**Pull request merged**
