### PR TITLE
Remove all fences

### LINKED ISSUE #45: Get rid of unnecessary fences
We have been very conservative in the past when we were forced to use UVM and added fences all over the place.  This need to be re-evaluated.

~~NB: Make sure to add UVM to the CI before starting to work on this~~ (addressed in #46)

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes #45.

### CODE REVIEW

**Comment by aprokop** [comment]
I think we would want to rebase this PR on top of #149 after that one is merged to make sure tests without UVM pass.

**Comment by masterleinad** [comment]
```
gpg: keyserver receive failed: No data

```

**Comment by aprokop** [comment]
Please rebase this PR on master.

**Comment by masterleinad** [comment]
> Please rebase this PR on master.

Done.

**Pull request merged**
