### PR TITLE
Switch SYCL build to Debug to speed it up

### PR DESCRIPTION
**Pull request by aprokop**
SYCL build takes a very long time:
Screen Shot 2020-12-30 at 9 47 43 AM

Looking closely in `.jenkins`, all builds are `Debug` except SYCL, which may explain the reason. The only downside is that we won't have any `Release` builds, but it's fine.

### CODE REVIEW

**Comment by dalg24** [comment]
```
ptxas fatal   : Unresolved extern function '__assert_fail'
```
I have seen similar issues before.  I think it comes from `assert` in kernel code.

**Comment by masterleinad** [comment]
> I have seen similar issues before. I think it comes from `assert` in kernel code.

Exactly, that is one of the reasons why I chose `Release` mode.

**Comment by masterleinad** [comment]
I am still trying to find ways to accelerate the build for `SYCL` also on the `Kokkos` side.

**Comment by masterleinad** [comment]
```
clang-12: error: unable to execute command: Segmentation fault (core dumped)
clang-12: error: ptxas command failed due to signal (use -v to see invocation)
```
... and that was the other reason why I went with `Release`.

**Comment by aprokop** [comment]
Trying out newer daily version of SYCL (2020-12-30) fails with
```
clang-12: error: unable to execute command: Executable "clang-offload-deps" doesn't exist!
clang-12: error: clang-offload-deps command failed with exit code 1 (use -v to see invocation)
```

**Comment by aprokop** [comment]
After a hack to copy `clang-offload-deps`, it is no better:
```                                                                                                                                                                                                                                                       
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.                                                                                                                                   
Stack dump:                                                                                                                                                                                                                                                             
0.  Program arguments: /opt/sycl/bin/clang-12 -cc1 -triple nvptx64-nvidia-cuda-sycldevice -fsycl -fsycl-is-device -fdeclare-spirv-builtins -aux-triple x86_64-unknown-linux-gnu -Wno-sycl-strict -sycl-std=2020 -S -disable-free -main-file-name tstDetailsCrsGraphWrapperImpl.cpp.o -mrelocation-model static -mframe-pointer=all -fno-rounding-math -fno-verbose-asm -no-integrated-as -aux-target-cpu x86-64 -internal-isystem /opt/sycl/bin/../include/sycl -mlink-builtin-bitcode /opt/sycl/lib/clang/12.0.0/../../clc/libspirv-nvptx64--nvidiacl.bc -mlink-builtin-bitcode /usr/local/cuda-10.2/nvvm/libdevice/libdevice.10.bc -target-feature +ptx65 -target-sdk-version=10.2 -target-cpu sm_50 -fno-split-dwarf-inlining -debug-info-kind=limited -dwarf-version=2 -debugger-tuning=gdb -resource-dir /opt/sycl/lib/clang/12.0.0 -Wpedantic -Wall -Wextra -Wno-unknown-cuda-version -fno-dwarf-directory-asm -fdebug-compilation-dir /var/jenkins/workspace/ArborX_PR-448/build/test -ferror-limit 19 -pthread -fgnuc-version=4.2.1 -o /tmp/tstDetailsCrsGraphWrapperImpl-277349.s -x ir /tmp/tstDetailsCrsGraphWrapperImpl-1f6af0.bc                                                                                                                                                                                                                           1.  Code generation                                                                                                                                                                                                                                                     2.  Running pass 'localaccessortosharedmemory' on module '/tmp/tstDetailsCrsGraphWrapperImpl-1f6af0.bc'.                                                                                                                                                                
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):                                                                                                                        
/opt/sycl/bin/clang-12(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamEi+0x2c)[0x55aa5abe7e7c]                                                                                                                                                                          
/opt/sycl/bin/clang-12(_ZN4llvm3sys17RunSignalHandlersEv+0x34)[0x55aa5abe5a34]                                                                                                                                                                                          
/opt/sycl/bin/clang-12(+0x20b1ba3)[0x55aa5abe5ba3]                                                                                                                                                                                                                      
/lib/x86_64-linux-gnu/libpthread.so.0(+0x128a0)[0x7f79caba38a0]                                                                                                                                                                                                         
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f79c9c9bf47]                                                                                                                                                                                                           
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f79c9c9d8b1]                                                                                                                                                                                                            
/lib/x86_64-linux-gnu/libc.so.6(+0x3042a)[0x7f79c9c8d42a]                                                                                                                                                                                                               
/lib/x86_64-linux-gnu/libc.so.6(+0x304a2)[0x7f79c9c8d4a2]                                                                                                                                                                                                               
/opt/sycl/bin/clang-12(+0x1052948)[0x55aa59b86948]                                                                                                                                                                                                                      
/opt/sycl/bin/clang-12(+0x1052b0a)[0x55aa59b86b0a]                                                                                                                                                                                                                      
/opt/sycl/bin/clang-12(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x376)[0x55aa5a4132e6]                                                                                                                                                                         
/opt/sycl/bin/clang-12(+0x238ffcf)[0x55aa5aec3fcf]                                                                                                                                                                                                                      
/opt/sycl/bin/clang-12(_ZN5clang17EmitBackendOutputERNS_17DiagnosticsEngineERKNS_19HeaderSearchOptionsERKNS_14CodeGenOptionsERKNS_13TargetOptionsERKNS_11LangOptionsERKN4llvm10DataLayoutEPNSE_6ModuleENS_13BackendActionESt10unique_ptrINSE_17raw_pwrite_streamESt14default_deleteISM_EE+0x5c5)[0x55aa5aec5da5]                                                                                                                                                                                                                                
/opt/sycl/bin/clang-12(_ZN5clang13CodeGenAction13ExecuteActionEv+0xb0b)[0x55aa5bb2687b]                                                                                                                                                                                 
/opt/sycl/bin/clang-12(_ZN5clang14FrontendAction7ExecuteEv+0xe1)[0x55aa5b4dd291]                                                                                                                                                                                        
/opt/sycl/bin/clang-12(_ZN5clang16CompilerInstance13ExecuteActionERNS_14FrontendActionE+0x302)[0x55aa5b485e92]                                                                                                                                                          
/opt/sycl/bin/clang-12(_ZN5clang25ExecuteCompilerInvocationEPNS_16CompilerInstanceE+0xb0a)[0x55aa5b5aa3ea]                                                                                                                                                              
/opt/sycl/bin/clang-12(_Z8cc1_mainN4llvm8ArrayRefIPKcEES2_Pv+0x11bc)[0x55aa598404ec]                                                                                                                                                                                    
/opt/sycl/bin/clang-12(+0xd069a9)[0x55aa5983a9a9]                                                                                                                                                                                                                       
/opt/sycl/bin/clang-12(main+0x780)[0x55aa597aeda0]                                                                                                                                                                                                                      
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f79c9c7eb97]                                                                                                                                                                                                 
/opt/sycl/bin/clang-12(_start+0x2a)[0x55aa5983a50a]                                                                                                                                                                                                                     
clang-12: error: unable to execute command: Aborted (core dumped)                                                                                                                                                                                                       
clang-12: error: clang frontend command failed due to signal (use -v to see invocation)
```

**Comment by aprokop** [comment]
Yeah, I guess `Debug` mode is not happening any time soon. Leaving SYCL as it is, hoping that @dalg24's tests splitting will speed up compilation (unlikely).

**Comment by aprokop** [comment]
Still failed:
```
clang-13: error: unable to execute command: Segmentation fault (core dumped)
clang-13: error: ptxas command failed due to signal (use -v to see invocation)
```

**Comment by aprokop** [comment]
Trying once again with the latest SYCL.

**Comment by masterleinad** [comment]
https://github.com/kokkos/kokkos/pull/3942 would likely help here (but then I would expect `Release` to be faster due to omitting all the debug symbols).

**Comment by aprokop** [comment]
Interestingly, updating both SYCL and OneAPI could not even build the container:
```
/scratch/kokkos/core/src/impl/Kokkos_Memory_Fence.hpp:61:9: error: no member named 'ONEAPI' in namespace 'sycl'

  sycl::ONEAPI::atomic_fence(sycl::ONEAPI::memory_order::acq_rel,
```

**Comment by masterleinad** [comment]
I'm not surprised if at all `Kokkos` `develop` could work. They deprecate (and remove) stuff in the compiler pretty frequently.

**Comment by aprokop** [comment]
> I'm not surprised if at all `Kokkos` `develop` could work. They deprecate (and remove) stuff in the compiler pretty frequently.

So is there a stable version we could use?

**Comment by masterleinad** [comment]
> So is there a stable version we could use?

Any commit one the develop branch should be fine. There haven't been any particular issues recently.

**Comment by aprokop** [comment]
The problem with `ptxas` seems to be due to using `assert()` inside the kernels (see intel/llvm#3385). It seems we could use the workaround in [this](https://github.com/intel/llvm/issues/3385#issuecomment-849783567) comment.

**Pull request closed without merging**
