### PR TITLE
Allow unmanaged views in sendAcrossNetwork

### LINKED ISSUE #419: sendAcrossNetwork should allow unmanaged views for export
Right now, using `exports` as unmanaged views is not possible due to a silly reason: when calling `doPostsAndWaits`, the `destBuffer` is created using `ExportView` type, while it must always be managed: https://github.com/arborx/ArborX/blob/06c0c2746314d05cfb757acf04731fd30c3a3f99/src/details/ArborX_DetailsDistributor.hpp#L261-L267 If permutation is necessary, it will be reallocated, which is not allowed for unmanaged views.

### PR DESCRIPTION
**Pull request by aprokop**
Fix #419.

### CODE REVIEW

**Comment by aprokop** [comment]
I'm sure @dalg24 will have strong views about how appending or removing memory traits from a view should work. I'm OK with any proposed changes to that part.

**Comment by dalg24** [comment]
I think you should just strip all the memory traits
```diff
diff --git a/src/details/ArborX_DetailsDistributor.hpp b/src/details/ArborX_DetailsDistributor.hpp
index fae7ed5..9cf1ab5 100644
--- a/src/details/ArborX_DetailsDistributor.hpp
+++ b/src/details/ArborX_DetailsDistributor.hpp
@@ -257,13 +257,15 @@ public:
         "");

     // This allows function to work even when ExportView is unmanaged.
-    using ManagedExportView =
-        typename UpdateMemoryTraits<ExportView, Kokkos::Unmanaged, false>::type;
+    using ExportViewWithoutMemoryTraits =
+        Kokkos::View<typename ExportView::data_type,
+                     typename ExportView::array_layout,
+                     typename ExportView::device_type>;

     using DestBufferMirrorViewType =
         decltype(ArborX::Details::create_layout_right_mirror_view_and_copy(
             std::declval<typename ImportView::memory_space>(),
-            std::declval<ManagedExportView>()));
+            std::declval<ExportViewWithoutMemoryTraits>()));

     constexpr int pointer_depth = internal::PointerDepth<
         typename DestBufferMirrorViewType::traits::data_type>::value;
@@ -282,7 +284,7 @@ public:
     bool const permutation_necessary = _permute.size() != 0;
     if (permutation_necessary)
     {
-      auto dest_buffer = ManagedExportView(
+      auto dest_buffer = ExportViewWithoutMemoryTraits(
           "ArborX::Distributor::doPostsAndWaits::destination_buffer",
           typename ExportView::array_layout{});

**Comment by aprokop** [comment]
> I think you should just strip all the memory traits

@dalg24 If this works, do you want me to retain history, or just overwrite on top?

**Comment by aprokop** [comment]
@dalg24 I pushed your patch. Let me know if you want to squash before merging, but I think it's OK to merge it in the current form if only to retain the patch of adding/removing memory traits.

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
