### PR TITLE
Check that work is enqueued on the user-provided execution space instance

### PR DESCRIPTION
**Pull request by dalg24**
Opening to use as a base for discussion

### CODE REVIEW

**Comment by aprokop** [comment]
Is it possible to catch the space used during view allocations? Are deep copies and creating mirror views already captured by the existing patch?

**Comment by dalg24** [comment]
> Is it possible to catch the space used during view allocations? Are deep copies and creating mirror views already captured by the existing patch?

Not possible without changes in Kokkos.  The device id not passed to the hooks neither for view allocations nor deep copy.  There is nothing special about creating mirrors, either we allocate or we don't.

**Comment by aprokop** [comment]
Rebased on master. I think this is a good idea, even if incomplete.

**Comment by aprokop** [comment]
Failures from constructor:
- `Kokkos::View::initialization [Testing::boxes_mirror]`
- `Kokkos::Tools::invoke_kokkosp_callback: Kokkos Profile Tool Fence`
- `Kokkos::View::destruction []`
- `Kokkos::Impl::ViewValueFunctor: View init/destroy fence`
- `HostSpace::impl_deallocate before free`

This is tricky.

**Comment by aprokop** [comment]
Splitting into two: parallel regions (this one) and fences (upcoming).

**Pull request merged**
