### PR TITLE
Fix DBSCAN test input file

### PR DESCRIPTION
**Pull request by aprokop**
I forgot to update this file when I changed the format of the input file in #523. Got lucky with the fact that the first coordinate was reading 3, so it was still thinking 3D file.

### CODE REVIEW

**Comment by aprokop** [comment]
@dalg24 Can you check if it fixes your segfault on Mac?

**Review by dalg24 — APPROVED** [review]
How comes test were still passing?  I was getting a segfault on my macmini.

**Comment by dalg24** [comment]
> @dalg24 Can you check if it fixes your segfault on Mac?

It runs without issue

**Comment by aprokop** [comment]
> How comes test were still passing? I was getting a segfault on my macmini.

No idea.

**Pull request merged**
