### PR TITLE
Try specifying custom CI build directory for gitlab

### LINKED ISSUE #634: Gitlab CI environment needs update
```
Ascent's OS was upgraded to RHEL 8 on February 11.  We strongly recommend
  rebuilding prior to running on upgraded system.
```
Besides updating the modules
```diff
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -11,7 +11,8 @@ stages:

 .LoadModules:
   before_script:
-    - module load gcc/7.4.0 cuda/10.1.243 cmake/3.18.2 git/2.20.1 spectrum-mpi/10.3.1.2-20200121
+    - module load gcc/7.5.0 cuda/10.1.243 cmake/3.22.2 git/2.31.1 spectrum-mpi/10.4.0.3-20210112
+      module list

 .BuildBoost:
   extends: .LoadModules
```
we also need to rebuild all the dependencies.

### PR DESCRIPTION
**Pull request by masterleinad**
This fixes #634 (again).

### CODE REVIEW

**Comment by masterleinad** [comment]
See https://code.ornl.gov/ecpcitest/alexa/-/pipelines/196094.

**Comment by aprokop** [comment]
How do you think this helps? My assumption was that it was due to the NFS filesystem that CMake configure fails. Does the new directory not use NFS?

**Comment by masterleinad** [comment]
Retest this please.

**Comment by aprokop** [comment]
@masterleinad You may want to use `[ci skip]` with this one.

**Review by aprokop — APPROVED** [review]

**Pull request merged**
