### PR TITLE
Introduce KokkosExt::sortByKey

### PR DESCRIPTION
**Pull request by aprokop**
Resurrecting and reorganizing #460.

### CODE REVIEW

**Comment by aprokop** [comment]
From Ascent (colored only):
```diff
-BM_construction<ArborX::BVH<Serial>>/1000/0/manual_time_median                                            +0.0891         +0.0860           438           476           446           485
-BM_construction<ArborX::BVH<Serial>>/1000/1/manual_time_median                                            +0.1345         +0.1318           413           468           422           477
-BM_construction<ArborX::BVH<OpenMP>>/1000/0/manual_time_median                                            +0.1735         +0.1627           281           330           302           351
-BM_radius_search<ArborX::BVH<OpenMP>>/1000/1000/10/1/0/0/2/manual_time_median                             +0.0942         +0.0927           618           677           635           694
-BM_radius_callback_search<ArborX::BVH<OpenMP>>/1000/1000/10/1/0/0/2/manual_time_median                    +0.1730         +0.1683           350           410           360           420
-BM_knn_search<ArborX::BVH<OpenMP>>/1000/1000/10/1/0/2/manual_time_median                                  +0.0727         +0.0712           690           741           707           758
-BM_knn_callback_search<ArborX::BVH<OpenMP>>/1000/1000/10/1/0/2/manual_time_median                         +0.0981         +0.0963           492           541           502           550
-BM_construction<ArborX::BVH<OpenMP>>/10000/0/manual_time_median                                           +0.1386         +0.1317           387           441           407           461
-BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/1/0/0/2/manual_time_median                           +0.0595         +0.0593          3027          3207          3043          3224
-BM_radius_callback_search<ArborX::BVH<OpenMP>>/10000/10000/10/1/0/0/2/manual_time_median                  +0.1124         +0.1115          1528          1700          1541          1712
-BM_construction<ArborX::BVH<OpenMP>>/100000/0/manual_time_median                                          +0.0613         +0.0605          1507          1600          1528          1620
-BM_radius_callback_search<ArborX::BVH<OpenMP>>/100000/100000/10/1/0/0/2/manual_time_median                +0.0964         +0.0857         13871         15208         13496         14653
-BM_construction<ArborX::BVH<OpenMP>>/1000/1/manual_time_median                                            +0.1744         +0.1630           284           333           304           354
-BM_radius_search<ArborX::BVH<OpenMP>>/1000/1000/10/1/0/1/3/manual_time_median                             +0.1149         +0.1115           485           541           502           558
-BM_radius_callback_search<ArborX::BVH<OpenMP>>/1000/1000/10/1/0/1/3/manual_time_median                    +0.2081         +0.2004           284           343           294           353
-BM_knn_search<ArborX::BVH<OpenMP>>/1000/1000/10/1/1/3/manual_time_median                                  +0.0823         +0.0808           644           697           661           715
-BM_knn_callback_search<ArborX::BVH<OpenMP>>/1000/1000/10/1/1/3/manual_time_median                         +0.1101         +0.1079           449           498           459           508
-BM_construction<ArborX::BVH<OpenMP>>/10000/1/manual_time_median                                           +0.1292         +0.1226           404           456           424           476
-BM_radius_search<ArborX::BVH<OpenMP>>/10000/10000/10/1/0/1/3/manual_time_median                           +0.0787         +0.0538          1847          1993          1327          1399
-BM_radius_callback_search<ArborX::BVH<OpenMP>>/10000/10000/10/1/0/1/3/manual_time_median                  +0.1341         +0.0893           964          1093           740           806
-BM_construction<ArborX::BVH<OpenMP>>/100000/1/manual_time_median                                          +0.0631         +0.0623          1732          1842          1753          1862
-BM_radius_search<ArborX::BVH<OpenMP>>/100000/100000/10/1/0/1/3/manual_time_median                         +0.0542         +0.0324         14668         15464          4241          4379
-BM_radius_callback_search<ArborX::BVH<OpenMP>>/100000/100000/10/1/0/1/3/manual_time_median                +0.0912         +0.0475          7631          8327          2676          2803
```
I don't trust any OpenMP results there, and not concerned. And it is expected that Serial is slower for the smallest sizes to the tune of 10-15% in construction and pure callbacks.

In general, I am not opposed to having this penalty if we think this PR is a step forward in the right direction.

**Comment by aprokop** [comment]
The only CI failure are warning from the SYCL container build.

**Comment by dalg24** [comment]
Posting here some of my notes on our current use of sorting

* This one could use regular sort with a custom compare
https://github.com/arborx/ArborX/blob/3efdbd705b0831d57eeff512a8c19930aa046d3c/examples/raytracing/example_raytracing.cpp#L353-L382
* This one should/should directly use `sortByKey`
https://github.com/arborx/ArborX/blob/3efdbd705b0831d57eeff512a8c19930aa046d3c/src/details/ArborX_DetailsDendrogram.hpp#L101-L119
* Another candidate for a custom compare and possibly for a variadic version of sortByKey
https://github.com/arborx/ArborX/blob/3efdbd705b0831d57eeff512a8c19930aa046d3c/src/details/ArborX_DetailsDistributedTreeImpl.hpp#L641-L658
* Another candidate for regular sort with custom compare
https://github.com/arborx/ArborX/blob/3efdbd705b0831d57eeff512a8c19930aa046d3c/src/details/ArborX_DetailsBatchedQueries.hpp#L51-L81

**Review by dalg24 — APPROVED** [review]
Looks good.  I agree this is the right direction.  I would be ok with specializing `sortObjects` if needed.

**Pull request merged**
