### PR TITLE
Use specified execution space in view allocations

### PR DESCRIPTION
**Pull request by dalg24**
Partial fix for #641

### CODE REVIEW

**Review by masterleinad — APPROVED** [review]
Looks OK to me.
In the end, specifying an execution space with `Kokkos::WithoutInitializing` shouldn't really matter but that's more like a `Kokkos` implementation detail and it shouldn't hurt to specify it nonetheless.

**Comment by dalg24** [comment]
> In the end, specifying an execution space with Kokkos::WithoutInitializing shouldn't really matter but that's more like a Kokkos implementation detail and it shouldn't hurt to specify it nonetheless.

Not true, may be used for an async allocation

**Comment by aprokop** [comment]
It is so verbose right now to create a view without initializing. Can we please introduce a macro to shorten that?

**Comment by dalg24** [comment]
> It is so verbose right now to create a view without initializing. Can we please introduce a macro to shorten that?

A macro? no.  A free function? sure.

**Comment by aprokop** [comment]
How about this:
```diff
-  Kokkos::View<ArborX::Point *, MemorySpace> particles(
-      Kokkos::view_alloc(execution_space, Kokkos::WithoutInitializing,
-                         "Example::points"), n);
+ Kokkos::View<ArborX::Point *, MemorySpace> particles(
+      KokkosExt::NoInit(execution_space, "Example::Points), n);
```
Less sure about the init version, it won't be any shorter. But could use `KokkosExt::Init` for consistency.
```diff
-  Kokkos::View<ArborX::Point *, MemorySpace> particles(
-      Kokkos::view_alloc(execution_space, "Example::points"), n);
+ Kokkos::View<ArborX::Point *, MemorySpace> particles(
+      KokkosExt::Init(execution_space, "Example::Points), n);
```

**Comment by dalg24** [comment]
I do not want to decide this in this PR

**Review by aprokop — COMMENTED** [review]
Overall, it looks fine. But I'd like to merge it together with free functions to reduce the verbosity.

**Comment by masterleinad** [comment]
Defining a free function sounds very close to going back to `Kokkos::ViewAllocateWithoutInitializing` which we wanted to deprecate in `Kokkos` but then didn't really. Hence, I'm not quite sure if that's a good direction.

**Comment by aprokop** [comment]
> I do not want to decide this in this PR

We don't have to merge with it. But I'd like to figure out if you are completely opposed to the idea, or see some value in it. If something like that is submitted as a PR, what are your arguments going to be?

**Comment by dalg24** [comment]
I don't think your current suggestions improves readability.  I am not convinced it is a problem we need to solve.

**Review by aprokop — APPROVED** [review]

**Pull request merged**
