### PR TITLE
Test SYCL with Kokkos 4.1.00

### PR DESCRIPTION
**Pull request by masterleinad**
There is not much of a point in testing with an intermediate version if we can use the release.
Drive-by: 
- We don't need to also install `icpc` but can restrict the Dockerfile to `icpx`. 
- We also need to update the base image, see https://github.com/kokkos/kokkos/pull/6288.

### CODE REVIEW

**Comment by masterleinad** [comment]
Retest this please.

**Review by aprokop — APPROVED** [review]
LGTM

**Comment by aprokop** [comment]
All builds (incl SYCL) passed (except for HIP waiting for a runner).

**Comment by aprokop** [comment]
Some warnings like
```
src/details/ArborX_MinimumSpanningTree.hpp:617:47:
warning: 'bit_cast<int, float>' is deprecated: use 'sycl::bit_cast' instead [-Wdeprecated-declarations]

        keys(e) = (key << shift) + KokkosExt::bit_cast<int>(edge.weight);

```
Don't know if they are new or not.

**Comment by masterleinad** [comment]
Ah, we can't really avoid this warning but it's harmless. Maybe, we just disable deprecation warnings for this build.

**Pull request merged**
