### PR TITLE
Fix Jenkins CI test logs

### PR DESCRIPTION
**Pull request by dalg24**

### CODE REVIEW

**Comment by dalg24** [comment]
Two options:
* either we pass flags to Boost.Test and Google benchmark to disable color in the console output,
* or wrap the shell steps in the Jenkinsfile using the ansicolor plugin

Any preference?

**Comment by dalg24** [comment]
The current change works around Jenkins truncating the logs.
Still need to fiddle with CTest settings (`CTEST_CUSTOM_MAXIMUM_PASSED_TEST_OUTPUT_SIZE` and such...)

**Comment by masterleinad** [comment]
This still gives
```
The rest of the test output was removed since it exceeds the threshold of 1024 bytes.
```

**Comment by masterleinad** [comment]
Can't you just pipe the output to `cat` (https://stackoverflow.com/questions/46117069/how-to-force-black-and-white-output-in-google-benchmark)?

**Comment by aprokop** [comment]
Is there anything that needs to be done here? Is it still a problem?

**Comment by dalg24** [comment]
> Is there anything that needs to be done here? Is it still a problem?

This is still a problem and I couldn't figure it out.

**Comment by aprokop** [comment]
From the thread description, it is not clear what exactly does not work. Is the current problem that something is still producing colored output?

**Comment by dalg24** [comment]
(Did not work though)

**Comment by aprokop** [comment]
> (Did not work though)

Please put in more details. What and why?

**Comment by dalg24** [comment]
https://cloud.cees.ornl.gov/jenkins-ci/blue/organizations/jenkins/ArborX/detail/PR-55/6/tests

```
Standard Output
Running 6 test cases...
[NON-XML-CHAR-0x1B][0;39;49m*** No errors detected
[NON-XML-CHAR-0x1B][0;39;49m
```

**Comment by dalg24** [comment]
Also `...[truncated 114 chars]...` in `ArborX_DistributedTree_Benchmark`

**Comment by dalg24** [comment]
I don't get why the standard output reported for the tests is still messed up.
The environment seems to be set properly in the builds and I this works on my local machine.
In any case these changes improve the jenkinsfile so I am in favor of merging as is.

**Comment by masterleinad** [comment]
The console output looks correct but the overview in Blue Ocean doesn't so it's seems to be some `xunit` problem.

**Pull request merged**
