### PR TITLE
Update ROCm to 4.0

### PR DESCRIPTION
**Pull request by aprokop**

### CODE REVIEW

**Comment by aprokop** [comment]
So, the HIP tester passed. But it does not mean anything, as it is sporadic. Is there a way for us to confirm if register leakage has been fixed? Or should we just merge this anyway, and let it run its course to see if we need #442 workaround?

**Comment by aprokop** [comment]
I restarted the build in Jenkins, and it passed the second time.

**Comment by dalg24** [comment]
You tested with 3.10
You forgot to update https://github.com/arborx/ArborX/blob/3a90c8f3b225881fb899fa03eda7f1b5ef97c364/.jenkins#L335

**Comment by aprokop** [comment]
> You tested with 3.10
> You forgot to update

😭

**Comment by masterleinad** [comment]
I would be fine with merging and seeing how it goes.

**Comment by aprokop** [comment]
@dalg24 Thoughts on this?

**Review by dalg24 — APPROVED** [review]

**Pull request merged**
