### PR TITLE
[WIP] Test Kokkos build with CMake

### PR DESCRIPTION
**Pull request by dalg24**
c.f. kokkos/kokkos#2104

### CODE REVIEW

**Comment by dalg24** [comment]
I meant to open a draft PR...

**Comment by masterleinad** [comment]
So just the usual problem with `BOOST_TEST`.

**Comment by masterleinad** [comment]
Looks like we are still missing to link the `cudart` library, but otherwise this looks OKish (modulo `boost`).

**Comment by masterleinad** [comment]
Superseded by #93.

**Pull request closed without merging**
