### PR TITLE
Remove no longer necessary Trilinos-specific code to allow building against Trilinos installation of Kokkos

### LINKED ISSUE #224: Make ArborX work with current Trilinos/Kokkos install
After Kokkos package was updated in Trilinos, we can no longer build ArborX against it. For example,
```
/home/xap/local/opt/trilinos-kokkos/include/OpenMP/Kokkos_OpenMP_Exec.hpp:51:2: error: #error "You enabled Kokkos OpenMP support without enabling OpenMP in t
he compiler!"
```

It seems that the code was restructured/modified. Some of the flags that used to be in `trilinos/lib/pkgconfig/kokkos.ps` (like `-fopenmp;--std=c++11`) were moved elsewhere (`trilinos/lib/cmake/Kokkos/KokkosConfig.cmake`). There is no `kokkos_generated_settings.cmake` anymore, either.

### PR DESCRIPTION
**Pull request by aprokop**
If desired, merging can be delayed until the required patch lands in Trilinos develop. Tested against kokkos/kokkos#2817 snapshotted into Trilinos (hash 669a373f4ff).

Fix #224

### CODE REVIEW

**Comment by masterleinad** [comment]
Yes, I am in favor of waiting a bit if this is fine with you.

**Comment by masterleinad** [comment]
I could at least confirm that this works if that is helpful.

**Comment by aprokop** [comment]
@masterleinad Please do, an extra confirmation would be nice. I did a PR to Kokkos today that you will need.

**Comment by aprokop** [comment]
I remove the 3.0 -> 3.1 change from this PR, I think that should be separate. Lets merge it in the current form, and then do a branch to do Kokkos 3.0 -> 3.1.

**Pull request merged**
